window.quizData = [
  {"word": "convention", "correct": "慣習", "choices": ["慣習", "難問"], "etymology": "コンベンション（/kʌnvˈenʃʌn/）", "example1": "It is a social convention in this country.", "jp1": "それはその国での社会的慣習だ。"},
  {"word": "supporter", "correct": "支持者", "choices": ["支持者", "航空機"], "etymology": "サポーター（/sʌpˈɔrtɝ/）", "example1": "Every team needs loyal supporters.", "jp1": "どのチームにも忠実な支持者が必要だ。"},
  {"word": "estate", "correct": "財産", "choices": ["財産", "報道官"], "etymology": "エステイト（/ɪstˈeɪt/）", "example1": "The house is part of a large estate.", "jp1": "その家は広い地所の一部だ。"},
  {"word": "treaty", "correct": "条約", "choices": ["条約", "課題"], "etymology": "トリーティ（/trˈiti/）", "example1": "The two nations signed a peace treaty.", "jp1": "その2国は平和条約に署名した。"},
  {"word": "ancestor", "correct": "祖先", "choices": ["祖先", "環境"], "etymology": "アンセスター（/ˈænsˌestɝ/）", "example1": "These people honored their ancestors.", "jp1": "その人々は祖先を敬った。"},
  {"word": "resident", "correct": "住民", "choices": ["住民", "援助"], "etymology": "レジデント（/rˈezɪdʌnt/）", "example1": "Every resident received a notice.", "jp1": "すべての住民が通知を受け取った。"},
  {"word": "collapse", "correct": "崩壊", "choices": ["崩壊", "宿泊施設"], "etymology": "コラプス（/kʌlˈæps/）", "example1": "The bridge was close to collapse.", "jp1": "その橋は崩壊寸前だった。"},
  {"word": "atmosphere", "correct": "雰囲気", "choices": ["雰囲気", "状態"], "etymology": "アトモスフィア（/ˈætmʌsfˌɪr/）", "example1": "The restaurant has a relaxed atmosphere.", "jp1": "そのレストランには落ち着いた雰囲気がある。"},
  {"word": "hearing", "correct": "聴聞会", "choices": ["聴聞会", "インフレ"], "etymology": "ヒアリング（/hˈirɪŋ/）", "example1": "The committee held a public hearing.", "jp1": "その委員会は公聴会を開いた。"},
  {"word": "instruction", "correct": "指示", "choices": ["指示", "指導者"], "etymology": "インストラクション（/ˌɪnstrˈʌkʃʌn/）", "example1": "Please read the instructions first.", "jp1": "まず説明書を読んでください。"},
  {"word": "structure", "correct": "構造", "choices": ["構造", "目的地"], "etymology": "ストラクチャー（/strˈʌktʃɝ/）", "example1": "The structure of the building is strong.", "jp1": "その建物の構造はしっかりしている。"},
  {"word": "telephone", "correct": "電話", "choices": ["電話", "基礎"], "etymology": "テレフォン（/tˈelʌfˌoʊn/）", "example1": "The telephone rang three times.", "jp1": "電話が3回鳴った。"},
  {"word": "sacrifice", "correct": "犠牲", "choices": ["犠牲", "つながり"], "etymology": "サクリファイス（/sˈækrʌfˌaɪs/）", "example1": "Success often requires sacrifice.", "jp1": "成功にはしばしば犠牲が必要だ。"},
  {"word": "interfere", "correct": "干渉", "choices": ["干渉", "反応"], "etymology": "インターフィア（/ˌɪntɝfˈɪr/）", "example1": "The noun use of interfere is rare.", "jp1": "interfere の名詞用法はまれだ。"},
  {"word": "lower", "correct": "下位", "choices": ["下位", "乗り物"], "etymology": "ロウアー（/lˈoʊɝ/）", "example1": "The noun use of lower is uncommon here.", "jp1": "lower の名詞用法はここではあまり一般的ではない。"},
  {"word": "crisis", "correct": "危機", "choices": ["危機", "存在"], "etymology": "クライシス（/krˈaɪsʌs/）", "example1": "The country is facing an economic crisis.", "jp1": "その国は経済危機に直面している。"},
  {"word": "passage", "correct": "一節", "choices": ["一節", "判断"], "etymology": "パッセージ（/pˈæsʌdʒ/）", "example1": "Read the passage and answer the questions.", "jp1": "その文章を読んで質問に答えなさい。"},
  {"word": "crime", "correct": "犯罪", "choices": ["犯罪", "エンジン"], "etymology": "クライム（/krˈaɪm/）", "example1": "The city has a low rate of crime.", "jp1": "その市は犯罪率が低い。"},
  {"word": "explanation", "correct": "説明", "choices": ["説明", "証拠"], "etymology": "エクスプラネーション（/ˌeksplʌnˈeɪʃʌn/）", "example1": "His explanation made sense.", "jp1": "彼の説明は筋が通っていた。"},
  {"word": "conversation", "correct": "会話", "choices": ["会話", "保護"], "etymology": "カンバセーション（/kˌɑnvɝsˈeɪʃʌn/）", "example1": "We had a long conversation after dinner.", "jp1": "私たちは夕食後に長い会話をした。"},
  {"word": "editor", "correct": "編集者", "choices": ["編集者", "正体"], "etymology": "エディター（/ˈedʌtɝ/）", "example1": "The editor checked the article.", "jp1": "その編集者は記事を確認した。"},
  {"word": "membership", "correct": "会員資格", "choices": ["会員資格", "文脈"], "etymology": "メンバーシップ（/mˈembɝʃˌɪp/）", "example1": "Gym membership is expensive here.", "jp1": "ここのジムの会員資格は高い。"},
  {"word": "politics", "correct": "政治", "choices": ["政治", "建設"], "etymology": "ポリティクス（/pˈɑlʌtˌɪks/）", "example1": "She is interested in politics.", "jp1": "彼女は政治に関心がある。"},
  {"word": "strategy", "correct": "戦略", "choices": ["戦略", "能力"], "etymology": "ストラテジー（/strˈætʌdʒi/）", "example1": "We need a better strategy.", "jp1": "私たちにはもっとよい戦略が必要だ。"},
  {"word": "regime", "correct": "体制", "choices": ["体制", "会期"], "etymology": "レジーム（/rʌʒˈim/）", "example1": "The regime lost public support.", "jp1": "その体制は国民の支持を失った。"},
  {"word": "teaching", "correct": "教えること", "choices": ["教えること", "文明"], "etymology": "ティーチング（/tˈitʃɪŋ/）", "example1": "Teaching requires patience.", "jp1": "教えることには忍耐が必要だ。"},
  {"word": "regulation", "correct": "規制", "choices": ["規制", "信念"], "etymology": "レギュレーション（/rˌeɡjʌlˈeɪʃʌn/）", "example1": "New regulations will start next month.", "jp1": "新しい規制は来月から始まる。"},
  {"word": "publication", "correct": "出版物", "choices": ["出版物", "発見"], "etymology": "パブリケーション（/pˌʌblɪkˈeɪʃʌn/）", "example1": "The publication of the book was delayed.", "jp1": "その本の出版は延期された。"},
  {"word": "religion", "correct": "宗教", "choices": ["宗教", "投資"], "etymology": "リリジョン（/rɪlˈɪdʒʌn/）", "example1": "Religion plays an important role in some societies.", "jp1": "宗教は社会によって重要な役割を果たす。"},
  {"word": "author", "correct": "著者", "choices": ["著者", "行為"], "etymology": "オーサー（/ˈɔθɝ/）", "example1": "The author wrote three novels.", "jp1": "その著者は3冊の小説を書いた。"},
  {"word": "administration", "correct": "行政", "choices": ["行政", "分析家"], "etymology": "アドミニストレーション（/ædmˌɪnɪstrˈeɪʃʌn/）", "example1": "The school administration approved the event.", "jp1": "学校の運営側がその行事を承認した。"},
  {"word": "reduction", "correct": "削減", "choices": ["削減", "影"], "etymology": "リダクション（/rʌdˈʌkʃʌn/）", "example1": "We need a reduction in costs.", "jp1": "私たちは費用の削減が必要だ。"},
  {"word": "possibility", "correct": "可能性", "choices": ["可能性", "免許"], "etymology": "ポシビリティ（/pˌɑsʌbˈɪlʌtˌi/）", "example1": "There is a strong possibility of rain.", "jp1": "雨が降る可能性が高い。"},
  {"word": "independence", "correct": "独立", "choices": ["独立", "欠席"], "etymology": "インディペンデンス（/ˌɪndɪpˈendʌns/）", "example1": "Children need some independence.", "jp1": "子どもにはある程度の自立が必要だ。"},
  {"word": "assumption", "correct": "仮定", "choices": ["仮定", "技術"], "etymology": "アサンプション（/ʌsˈʌmpʃʌn/）", "example1": "That assumption is not always true.", "jp1": "その仮定はいつも正しいとは限らない。"},
  {"word": "facility", "correct": "施設", "choices": ["施設", "配達"], "etymology": "ファシリティ（/fʌsˈɪlɪti/）", "example1": "The sports facility is open every day.", "jp1": "そのスポーツ施設は毎日開いている。"},
  {"word": "relief", "correct": "安心", "choices": ["安心", "締め切り"], "etymology": "リリーフ（/rɪlˈif/）", "example1": "It was a relief to hear the good news.", "jp1": "そのよい知らせを聞いて安心した。"},
  {"word": "proceeding", "correct": "議事", "choices": ["議事", "従業員"], "etymology": "プロシーディング（/prʌsˈidɪŋ/）", "example1": "The proceedings began at noon.", "jp1": "その議事は正午に始まった。"},
  {"word": "unemployment", "correct": "失業", "choices": ["失業", "懸念"], "etymology": "アンインプロイメント（/ˌʌnɪmplˈɔɪmʌnt/）", "example1": "Unemployment rose this year.", "jp1": "今年は失業が増えた。"},
  {"word": "experiment", "correct": "実験", "choices": ["実験", "湿度"], "etymology": "エクスペリメント（/ɪkspˈerʌmʌnt/）", "example1": "The students conducted a simple experiment.", "jp1": "生徒たちは簡単な実験を行った。"},
  {"word": "improvement", "correct": "改善", "choices": ["改善", "目標"], "etymology": "インプルーブメント（/ˌɪmprˈuvmʌnt/）", "example1": "I can see a big improvement in your writing.", "jp1": "あなたの書く力には大きな改善が見られる。"},
  {"word": "string", "correct": "ひも", "choices": ["ひも", "公開"], "etymology": "ストリング（/strˈɪŋ/）", "example1": "The bag was tied with a string.", "jp1": "その袋はひもで結ばれていた。"},
  {"word": "commission", "correct": "委員会", "choices": ["委員会", "生産高"], "etymology": "コミッション（/kʌmˈɪʃʌn/）", "example1": "The commission published its report.", "jp1": "その委員会は報告書を発表した。"},
  {"word": "consideration", "correct": "考慮", "choices": ["考慮", "監視装置"], "etymology": "コンシダレーション（/kʌnsˌɪdɝˈeɪʃʌn/）", "example1": "Cost was an important consideration.", "jp1": "費用は重要な検討事項だった。"},
  {"word": "software", "correct": "ソフトウェア", "choices": ["ソフトウェア", "財政"], "etymology": "ソフトウェア（/ˈsɔftˌwɛr/）", "example1": "This software is easy to use.", "jp1": "このソフトウェアは使いやすい。"},
  {"word": "priority", "correct": "優先事項", "choices": ["優先事項", "進歩"], "etymology": "プライオリティ（/praɪˈɔrʌti/）", "example1": "Safety is our top priority.", "jp1": "安全が私たちの最優先事項だ。"},
  {"word": "enquiry", "correct": "問い合わせ", "choices": ["問い合わせ", "魅力"], "etymology": "インクワイアリー（/ɪnkwˈaɪrˌi/）", "example1": "Please send your enquiry by email.", "jp1": "お問い合わせはメールで送ってください。"},
  {"word": "revenue", "correct": "収益", "choices": ["収益", "再検討"], "etymology": "レベニュー（/rˈevʌnˌu/）", "example1": "The company increased its revenue.", "jp1": "その会社は収益を増やした。"},
  {"word": "literature", "correct": "文学", "choices": ["文学", "料金"], "etymology": "リテラチャー（/lˈɪtɝʌtʃɝ/）", "example1": "She studies English literature.", "jp1": "彼女は英文学を学んでいる。"},
  {"word": "marriage", "correct": "結婚", "choices": ["結婚", "措置"], "etymology": "マリッジ（/mˈerɪdʒ/）", "example1": "Their marriage lasted forty years.", "jp1": "彼らの結婚生活は40年続いた。"},
  {"word": "appearance", "correct": "外見", "choices": ["外見", "取っ手"], "etymology": "アピアランス（/ʌpˈɪrʌns/）", "example1": "His appearance has changed a lot.", "jp1": "彼の外見は大きく変わった。"},
  {"word": "occasion", "correct": "場合", "choices": ["場合", "願望"], "etymology": "オケイジョン（/ʌkˈeɪʒʌn/）", "example1": "This cake is for a special occasion.", "jp1": "このケーキは特別な機会のためのものだ。"},
  {"word": "factor", "correct": "要因", "choices": ["要因", "記録"], "etymology": "ファクター（/fˈæktɝ/）", "example1": "Time is an important factor.", "jp1": "時間は重要な要因だ。"},
  {"word": "strength", "correct": "強み", "choices": ["強み", "説明"], "etymology": "ストレングス（/strˈeŋkθ/）", "example1": "Her strength is patience.", "jp1": "彼女の強みは忍耐だ。"},
  {"word": "executive", "correct": "役員", "choices": ["役員", "戦い"], "etymology": "イグゼクティブ（/ɪɡzˈekjʌtɪv/）", "example1": "The executive made the final decision.", "jp1": "その役員が最終決定を下した。"},
  {"word": "location", "correct": "場所", "choices": ["場所", "沈黙"], "etymology": "ロケーション（/loʊkˈeɪʃʌn/）", "example1": "The hotel is in a convenient location.", "jp1": "そのホテルは便利な場所にある。"},
  {"word": "prospect", "correct": "見通し", "choices": ["見通し", "開始"], "etymology": "プロスペクト（/prˈɑspekt/）", "example1": "Job prospects are better now.", "jp1": "仕事の見通しは今のほうがよい。"},
  {"word": "colleague", "correct": "同僚", "choices": ["同僚", "演出"], "etymology": "コリーグ（/kˈɑliɡ/）", "example1": "A colleague helped me with the report.", "jp1": "同僚が私の報告書を手伝ってくれた。"},
  {"word": "enterprise", "correct": "企業", "choices": ["企業", "敬意"], "etymology": "エンタープライズ（/ˈentɝprˌaɪz/）", "example1": "The enterprise created many jobs.", "jp1": "その企業は多くの雇用を生み出した。"},
  {"word": "pressure", "correct": "圧力", "choices": ["圧力", "対比"], "etymology": "プレッシャー（/prˈeʃɝ/）", "example1": "He works well under pressure.", "jp1": "彼はプレッシャーの中でもうまく働く。"},
  {"word": "consequence", "correct": "結果", "choices": ["結果", "討論"], "etymology": "コンシクウェンス（/kˈɑnsʌkwʌns/）", "example1": "Every action has a consequence.", "jp1": "どんな行動にも結果がある。"},
  {"word": "instance", "correct": "例", "choices": ["例", "ごちそう"], "etymology": "インスタンス（/ˈɪnstʌns/）", "example1": "This is a good instance of teamwork.", "jp1": "これはチームワークのよい例だ。"},
  {"word": "inquiry", "correct": "調査", "choices": ["調査", "方法"], "etymology": "インクワイアリー（/ˌɪnkwˈaɪrˌi/）", "example1": "The police began an inquiry.", "jp1": "警察は調査を始めた。"},
  {"word": "reader", "correct": "読者", "choices": ["読者", "蓄え"], "etymology": "リーダー（/rˈidɝ/）", "example1": "This magazine is popular with young readers.", "jp1": "この雑誌は若い読者に人気がある。"},
  {"word": "theory", "correct": "理論", "choices": ["理論", "物体"], "etymology": "セオリー（/θˈɪri/）", "example1": "His theory is difficult to prove.", "jp1": "彼の理論は証明するのが難しい。"},
  {"word": "cancer", "correct": "がん", "choices": ["がん", "疑い"], "etymology": "キャンサー（/kˈænsɝ/）", "example1": "Doctors detected the cancer early.", "jp1": "医師たちはがんを早期に発見した。"},
  {"word": "incident", "correct": "事件", "choices": ["事件", "賞"], "etymology": "インシデント（/ˈɪnsʌdʌnt/）", "example1": "The incident happened last week.", "jp1": "その事件は先週起こった。"},
  {"word": "volume", "correct": "量", "choices": ["量", "難題"], "etymology": "ボリューム（/vˈɑljum/）", "example1": "Please turn down the volume.", "jp1": "音量を下げてください。"},
  {"word": "creation", "correct": "創造", "choices": ["創造", "殺人"], "etymology": "クリエーション（/kriˈeɪʃʌn/）", "example1": "The creation of the park took two years.", "jp1": "その公園の造成には2年かかった。"},
  {"word": "conflict", "correct": "対立", "choices": ["対立", "支部"], "etymology": "コンフリクト（/kˈɑnflɪkt/）", "example1": "The conflict lasted for decades.", "jp1": "その対立は何十年も続いた。"},
  {"word": "historian", "correct": "歴史家", "choices": ["歴史家", "供給"], "etymology": "ヒストリアン（/hɪstˈɔriʌn/）", "example1": "The historian wrote a famous book.", "jp1": "その歴史家は有名な本を書いた。"},
  {"word": "sentence", "correct": "文", "choices": ["文", "形"], "etymology": "センテンス（/sˈentʌns/）", "example1": "This sentence is too long.", "jp1": "この文は長すぎる。"},
  {"word": "studio", "correct": "スタジオ", "choices": ["スタジオ", "衝撃"], "etymology": "スタジオ（/stˈudiˌoʊ/）", "example1": "The program was recorded in a studio.", "jp1": "その番組はスタジオで録画された。"},
  {"word": "puzzle", "correct": "難問", "choices": ["難問", "抗議"], "etymology": "パズル（/pˈʌzʌl/）", "example1": "This puzzle is harder than it looks.", "jp1": "このパズルは見た目より難しい。"},
  {"word": "aircraft", "correct": "航空機", "choices": ["航空機", "向上"], "etymology": "エアクラフト（/ˈerkrˌæft/）", "example1": "The aircraft landed safely.", "jp1": "その航空機は無事に着陸した。"},
  {"word": "spokesman", "correct": "報道官", "choices": ["報道官", "捜索"], "etymology": "スポークスマン（/spˈoʊksmʌn/）", "example1": "The spokesman answered questions from reporters.", "jp1": "その報道官は記者たちの質問に答えた。"},
  {"word": "assignment", "correct": "課題", "choices": ["課題", "試み"], "etymology": "アサインメント（/ʌsˈaɪnmʌnt/）", "example1": "We have a writing assignment this week.", "jp1": "今週は作文の課題がある。"},
  {"word": "setting", "correct": "環境", "choices": ["環境", "展示"], "etymology": "セッティング（/sˈetɪŋ/）", "example1": "The story has an unusual setting.", "jp1": "その物語には変わった舞台設定がある。"},
  {"word": "assistance", "correct": "援助", "choices": ["援助", "利益"], "etymology": "アシスタンス（/ʌsˈɪstʌns/）", "example1": "Thank you for your assistance.", "jp1": "ご支援ありがとうございます。"},
  {"word": "accommodation", "correct": "宿泊施設", "choices": ["宿泊施設", "事柄"], "etymology": "アコモデーション（/ʌkˌɑmʌdˈeɪʃʌn/）", "example1": "We need accommodation for two nights.", "jp1": "私たちには2泊分の宿泊施設が必要だ。"}
];
