window.quizData = [
  {"word": "welfare", "correct": "福祉", "choices": ["福祉", "記述"], "etymology": "ウェルフェア（/wˈelfˌer/）", "example1": "The city spends more money on public welfare.", "jp1": "その市は公共福祉により多くのお金を使っている。"},
  {"word": "exhibition", "correct": "展示会", "choices": ["展示会", "兵士"], "etymology": "エキシビション（/ˌeksʌbˈɪʃʌn/）", "example1": "We visited an art exhibition yesterday.", "jp1": "私たちは昨日美術展を見に行った。"},
  {"word": "negotiation", "correct": "交渉", "choices": ["交渉", "比較"], "etymology": "ネゴシエーション（/nɪɡˌoʊʃiˈeɪʃʌn/）", "example1": "The two companies are in negotiation now.", "jp1": "その2社は今交渉中だ。"},
  {"word": "parliament", "correct": "議会", "choices": ["議会", "認識"], "etymology": "パーラメント（/pˈɑrlʌmʌnt/）", "example1": "The law was discussed in parliament.", "jp1": "その法律は議会で議論された。"},
  {"word": "substitute", "correct": "代用品", "choices": ["代用品", "けが"], "etymology": "サブスティテュート（/sˈʌbstʌtˌut/）", "example1": "Soy milk is a good substitute for cow's milk.", "jp1": "豆乳は牛乳のよい代用品だ。"},
  {"word": "stranger", "correct": "見知らぬ人", "choices": ["見知らぬ人", "正義"], "etymology": "ストレンジャー（/strˈeɪndʒɝ/）", "example1": "Do not talk to a stranger at night.", "jp1": "夜に見知らぬ人に話しかけてはいけない。"},
  {"word": "opposition", "correct": "反対", "choices": ["反対", "構成要素"], "etymology": "オポジション（/ˌɑpʌzˈɪʃʌn/）", "example1": "There was strong opposition to the new rule.", "jp1": "その新しい規則には強い反対があった。"},
  {"word": "district", "correct": "地区", "choices": ["地区", "慣習"], "etymology": "ディストリクト（/dˈɪstrɪkt/）", "example1": "This district is famous for its old buildings.", "jp1": "この地区は古い建物で有名だ。"},
  {"word": "invent", "correct": "発明", "choices": ["発明", "支持者"], "etymology": "インベント（/ˌɪnvˈent/）", "example1": "The noun use of invent is rare.", "jp1": "invent の名詞用法はまれだ。"},
  {"word": "leadership", "correct": "指導力", "choices": ["指導力", "財産"], "etymology": "リーダーシップ（/lˈidɝʃˌɪp/）", "example1": "Good leadership can change a team.", "jp1": "よい指導力はチームを変えることができる。"},
  {"word": "proportion", "correct": "割合", "choices": ["割合", "条約"], "etymology": "プロポーション（/prʌpˈɔrʃʌn/）", "example1": "A large proportion of the budget went to education.", "jp1": "予算の大部分が教育に使われた。"},
  {"word": "exception", "correct": "例外", "choices": ["例外", "祖先"], "etymology": "エクセプション（/ɪksˈepʃʌn/）", "example1": "There is one exception to this rule.", "jp1": "この規則には1つ例外がある。"},
  {"word": "insult", "correct": "侮辱", "choices": ["侮辱", "住民"], "etymology": "インサルト（/ˌɪnsˈʌlt/）", "example1": "His words were taken as an insult.", "jp1": "彼の言葉は侮辱と受け取られた。"},
  {"word": "purchase", "correct": "購入", "choices": ["購入", "崩壊"], "etymology": "パーチェス（/pˈɝtʃʌs/）", "example1": "This purchase was a good decision.", "jp1": "この購入はよい判断だった。"},
  {"word": "device", "correct": "装置", "choices": ["装置", "雰囲気"], "etymology": "ディバイス（/dɪvˈaɪs/）", "example1": "This device measures temperature.", "jp1": "この装置は温度を測る。"},
  {"word": "tension", "correct": "緊張", "choices": ["緊張", "聴聞会"], "etymology": "テンション（/tˈenʃʌn/）", "example1": "There was tension in the room.", "jp1": "その部屋には緊張感があった。"},
  {"word": "concept", "correct": "概念", "choices": ["概念", "指示"], "etymology": "コンセプト（/kˈɑnsept/）", "example1": "The concept is easy to understand.", "jp1": "その概念は理解しやすい。"},
  {"word": "threat", "correct": "脅威", "choices": ["脅威", "構造"], "etymology": "スレット（/θrˈet/）", "example1": "Climate change is a serious threat.", "jp1": "気候変動は深刻な脅威だ。"},
  {"word": "violence", "correct": "暴力", "choices": ["暴力", "電話"], "etymology": "バイオレンス（/vˈaɪʌlʌns/）", "example1": "The movie contains some violence.", "jp1": "その映画にはいくらか暴力的な場面が含まれている。"},
  {"word": "channel", "correct": "経路", "choices": ["経路", "犠牲"], "etymology": "チャンネル（/tʃˈænʌl/）", "example1": "We changed the TV channel.", "jp1": "私たちはテレビのチャンネルを変えた。"},
  {"word": "ministry", "correct": "省庁", "choices": ["省庁", "干渉"], "etymology": "ミニストリー（/mˈɪnʌstri/）", "example1": "The ministry announced a new policy.", "jp1": "その省は新しい方針を発表した。"},
  {"word": "network", "correct": "ネットワーク", "choices": ["ネットワーク", "下位"], "etymology": "ネットワーク（/nˈetwˌɝk/）", "example1": "The computer is connected to the network.", "jp1": "そのコンピューターはネットワークにつながっている。"},
  {"word": "professor", "correct": "教授", "choices": ["教授", "危機"], "etymology": "プロフェッサー（/prʌfˈesɝ/）", "example1": "The professor gave a clear lecture.", "jp1": "その教授はわかりやすい講義をした。"},
  {"word": "advantage", "correct": "利点", "choices": ["利点", "一節"], "etymology": "アドバンテージ（/ædvˈæntɪdʒ/）", "example1": "One advantage of this system is speed.", "jp1": "この制度の利点の1つは速さだ。"},
  {"word": "agriculture", "correct": "農業", "choices": ["農業", "犯罪"], "etymology": "アグリカルチャー（/ˈæɡrɪkˌʌltʃɝ/）", "example1": "Agriculture is important in this region.", "jp1": "この地域では農業が重要だ。"},
  {"word": "interpretation", "correct": "解釈", "choices": ["解釈", "説明"], "etymology": "インタープリテーション（/ˌɪntˌɝprɪtˈeɪʃʌn/）", "example1": "Her interpretation of the poem was interesting.", "jp1": "彼女のその詩の解釈は興味深かった。"},
  {"word": "healthcare", "correct": "医療", "choices": ["医療", "会話"], "etymology": "ヘルスケア（/ˈhɛlθˌkɛr/）", "example1": "Everyone should have access to healthcare.", "jp1": "すべての人が医療を受けられるべきだ。"},
  {"word": "behavior", "correct": "行動", "choices": ["行動", "編集者"], "etymology": "ビヘイビア（/bɪhˈeɪvjɝ/）", "example1": "His behavior surprised everyone.", "jp1": "彼の行動はみんなを驚かせた。"},
  {"word": "offence", "correct": "違反", "choices": ["違反", "会員資格"], "etymology": "オフェンス", "example1": "Speeding is a traffic offence.", "jp1": "スピード違反は交通違反だ。"},
  {"word": "implication", "correct": "含意", "choices": ["含意", "政治"], "etymology": "インプリケーション（/ˌɪmplʌkˈeɪʃʌn/）", "example1": "The decision has serious implications.", "jp1": "その決定は重大な意味合いを持つ。"},
  {"word": "pension", "correct": "年金", "choices": ["年金", "戦略"], "etymology": "ペンション（/pˈenʃʌn/）", "example1": "My grandfather lives on a small pension.", "jp1": "祖父は少ない年金で暮らしている。"},
  {"word": "movement", "correct": "運動", "choices": ["運動", "体制"], "etymology": "ムーブメント（/mˈuvmʌnt/）", "example1": "The movement for reform is growing.", "jp1": "改革を求める運動は広がっている。"},
  {"word": "significance", "correct": "重要性", "choices": ["重要性", "教えること"], "etymology": "シグニフィカンス（/sʌɡnˈɪfɪkʌns/）", "example1": "We studied the significance of the event.", "jp1": "私たちはその出来事の重要性を学んだ。"},
  {"word": "status", "correct": "地位", "choices": ["地位", "規制"], "etymology": "ステータス（/stˈætʌs/）", "example1": "He checked the status of his order online.", "jp1": "彼は注文の状況をオンラインで確認した。"},
  {"word": "resemble", "correct": "類似", "choices": ["類似", "出版物"], "etymology": "リゼンブル（/rɪzˈembʌl/）", "example1": "The noun use of resemble is rare.", "jp1": "resemble の名詞用法はまれだ。"},
  {"word": "quality", "correct": "質", "choices": ["質", "宗教"], "etymology": "クオリティ（/kwˈɑlʌti/）", "example1": "The quality of the food was excellent.", "jp1": "その食べ物の質はすばらしかった。"},
  {"word": "reminder", "correct": "注意喚起", "choices": ["注意喚起", "著者"], "etymology": "リマインダー（/rimˈaɪndɝ/）", "example1": "This note is a helpful reminder.", "jp1": "このメモは役に立つ注意喚起だ。"},
  {"word": "development", "correct": "発展", "choices": ["発展", "行政"], "etymology": "ディベロップメント（/dɪvˈelʌpmʌnt/）", "example1": "The town has seen rapid development.", "jp1": "その町は急速な発展を経験してきた。"},
  {"word": "criterion", "correct": "基準", "choices": ["基準", "削減"], "etymology": "クライテリアン（/kraɪtˈɪriʌn/）", "example1": "Price is an important criterion.", "jp1": "価格は重要な判断基準だ。"},
  {"word": "surgery", "correct": "手術", "choices": ["手術", "可能性"], "etymology": "サージャリー（/sˈɝdʒɝi/）", "example1": "She had surgery on her knee.", "jp1": "彼女はひざの手術を受けた。"},
  {"word": "currency", "correct": "通貨", "choices": ["通貨", "独立"], "etymology": "カレンシー（/kˈɝʌnsi/）", "example1": "The euro is the local currency there.", "jp1": "ユーロはそこで使われている通貨だ。"},
  {"word": "emphasis", "correct": "強調", "choices": ["強調", "仮定"], "etymology": "エンファシス（/ˈemfʌsʌs/）", "example1": "The course places emphasis on writing.", "jp1": "その授業は書くことに重点を置いている。"},
  {"word": "director", "correct": "監督", "choices": ["監督", "施設"], "etymology": "ダイレクター（/dɝˈektɝ/）", "example1": "The director spoke to the staff.", "jp1": "その監督はスタッフに話をした。"},
  {"word": "ingredient", "correct": "材料", "choices": ["材料", "安心"], "etymology": "イングリーディエント（/ˌɪnɡrˈidiʌnt/）", "example1": "Sugar is the main ingredient.", "jp1": "砂糖が主な材料だ。"},
  {"word": "equipment", "correct": "設備", "choices": ["設備", "議事"], "etymology": "イクイップメント（/ɪkwˈɪpmʌnt/）", "example1": "The lab has modern equipment.", "jp1": "その研究室には最新の設備がある。"},
  {"word": "vision", "correct": "展望", "choices": ["展望", "失業"], "etymology": "ビジョン（/vˈɪʒʌn/）", "example1": "The company has a clear vision for the future.", "jp1": "その会社は将来について明確な展望を持っている。"},
  {"word": "republic", "correct": "共和国", "choices": ["共和国", "実験"], "etymology": "リパブリック（/ripˈʌblʌk/）", "example1": "France is a republic.", "jp1": "フランスは共和国だ。"},
  {"word": "document", "correct": "文書", "choices": ["文書", "改善"], "etymology": "ドキュメント（/dˈɑkjʌment/）", "example1": "Please read the document carefully.", "jp1": "その文書を注意深く読んでください。"},
  {"word": "county", "correct": "郡", "choices": ["郡", "ひも"], "etymology": "カウンティ（/kˈaʊnti/）", "example1": "He lives in a rural county.", "jp1": "彼は田舎の郡に住んでいる。"},
  {"word": "quarter", "correct": "4分の1", "choices": ["4分の1", "委員会"], "etymology": "クォーター（/kwˈɔrtɝ/）", "example1": "A quarter of the students were absent.", "jp1": "その学生の4分の1が欠席した。"},
  {"word": "solicitor", "correct": "事務弁護士", "choices": ["事務弁護士", "考慮"], "etymology": "ソリシター（/sʌlˈɪsʌtɝ/）", "example1": "She spoke with her solicitor.", "jp1": "彼女は事務弁護士に相談した。"},
  {"word": "legislation", "correct": "法律", "choices": ["法律", "ソフトウェア"], "etymology": "レジスレーション（/lˌedʒʌslˈeɪʃʌn/）", "example1": "New legislation was introduced last year.", "jp1": "新しい法律が昨年導入された。"},
  {"word": "democracy", "correct": "民主主義", "choices": ["民主主義", "優先事項"], "etymology": "デモクラシー（/dɪmˈɑkrʌsi/）", "example1": "Democracy depends on free elections.", "jp1": "民主主義は自由な選挙に支えられている。"},
  {"word": "version", "correct": "版", "choices": ["版", "問い合わせ"], "etymology": "バージョン（/vˈɝʒʌn/）", "example1": "This is the latest version of the app.", "jp1": "これはそのアプリの最新バージョンだ。"},
  {"word": "failure", "correct": "失敗", "choices": ["失敗", "収益"], "etymology": "フェイリャー（/fˈeɪljɝ/）", "example1": "The plan ended in failure.", "jp1": "その計画は失敗に終わった。"},
  {"word": "servant", "correct": "使用人", "choices": ["使用人", "文学"], "etymology": "サーバント（/sˈɝvʌnt/）", "example1": "The story is about a young servant.", "jp1": "その物語は若い使用人についてのものだ。"},
  {"word": "holder", "correct": "保有者", "choices": ["保有者", "結婚"], "etymology": "ホルダー（/hˈoʊldɝ/）", "example1": "Ticket holders may enter first.", "jp1": "チケットの所持者は先に入場できる。"},
  {"word": "category", "correct": "部類", "choices": ["部類", "外見"], "etymology": "カテゴリー（/kˈætʌɡˌɔri/）", "example1": "This book belongs in a different category.", "jp1": "この本は別の分類に入る。"},
  {"word": "neighbour", "correct": "近所の人", "choices": ["近所の人", "場合"], "etymology": "ネイバー（/nˈeɪbɝ/）", "example1": "Our neighbour is very kind.", "jp1": "私たちの近所の人はとても親切だ。"},
  {"word": "breath", "correct": "息", "choices": ["息", "要因"], "etymology": "ブレス（/brˈeθ/）", "example1": "Take a deep breath and relax.", "jp1": "深呼吸して落ち着きなさい。"},
  {"word": "requirement", "correct": "必要条件", "choices": ["必要条件", "強み"], "etymology": "リクワイアメント（/rɪkwˈaɪrmʌnt/）", "example1": "English is a requirement for this job.", "jp1": "この仕事には英語が必要条件だ。"},
  {"word": "president", "correct": "大統領", "choices": ["大統領", "役員"], "etymology": "プレジデント（/prˈezʌdˌent/）", "example1": "The president gave a speech.", "jp1": "大統領は演説をした。"},
  {"word": "suggestion", "correct": "提案", "choices": ["提案", "場所"], "etymology": "サジェスチョン（/sʌdʒˈestʃʌn/）", "example1": "Thank you for your suggestion.", "jp1": "提案をありがとうございます。"},
  {"word": "pleasure", "correct": "喜び", "choices": ["喜び", "見通し"], "etymology": "プレジャー（/plˈeʒɝ/）", "example1": "It was a pleasure to meet you.", "jp1": "お会いできてうれしかったです。"},
  {"word": "league", "correct": "連盟", "choices": ["連盟", "同僚"], "etymology": "リーグ（/lˈiɡ/）", "example1": "Our team joined a local league.", "jp1": "私たちのチームは地元のリーグに入った。"},
  {"word": "intention", "correct": "意図", "choices": ["意図", "企業"], "etymology": "インテンション（/ˌɪntˈentʃʌn/）", "example1": "His intention was good.", "jp1": "彼の意図はよかった。"},
  {"word": "decade", "correct": "10年間", "choices": ["10年間", "圧力"], "etymology": "デケイド（/dekˈeɪd/）", "example1": "A decade has passed since then.", "jp1": "それから10年が過ぎた。"},
  {"word": "prison", "correct": "刑務所", "choices": ["刑務所", "結果"], "etymology": "プリズン（/prˈɪzʌn/）", "example1": "He spent ten years in prison.", "jp1": "彼は10年間刑務所にいた。"},
  {"word": "sequence", "correct": "連続", "choices": ["連続", "例"], "etymology": "シークエンス（/sˈikwʌns/）", "example1": "Put the pictures in the correct sequence.", "jp1": "絵を正しい順番に並べなさい。"},
  {"word": "initiative", "correct": "主導権", "choices": ["主導権", "調査"], "etymology": "イニシアティブ（/ˌɪnˈɪʃʌtɪv/）", "example1": "She took the initiative and solved the problem.", "jp1": "彼女は自ら進んで問題を解決した。"},
  {"word": "response", "correct": "反応", "choices": ["反応", "読者"], "etymology": "リスポンス（/rɪspˈɑns/）", "example1": "We are waiting for their response.", "jp1": "私たちは彼らの返答を待っている。"},
  {"word": "characteristic", "correct": "特徴", "choices": ["特徴", "理論"], "etymology": "キャラクタリスティック（/kˌerʌktɝˈɪstɪk/）", "example1": "Patience is an important characteristic of a teacher.", "jp1": "忍耐は教師の重要な特性だ。"},
  {"word": "variety", "correct": "多様性", "choices": ["多様性", "がん"], "etymology": "バラエティ（/vɝˈaɪʌti/）", "example1": "The store sells a variety of snacks.", "jp1": "その店はいろいろな種類の菓子を売っている。"},
  {"word": "description", "correct": "記述", "choices": ["記述", "事件"], "etymology": "ディスクリプション（/dɪskrˈɪpʃʌn/）", "example1": "Your description was very accurate.", "jp1": "あなたの描写はとても正確だった。"},
  {"word": "soldier", "correct": "兵士", "choices": ["兵士", "量"], "etymology": "ソルジャー（/sˈoʊldʒɝ/）", "example1": "The soldier returned home safely.", "jp1": "その兵士は無事に帰宅した。"},
  {"word": "comparison", "correct": "比較", "choices": ["比較", "創造"], "etymology": "コンパリスン（/kʌmpˈerʌsʌn/）", "example1": "The report includes a comparison of the two systems.", "jp1": "その報告書には2つの制度の比較が含まれている。"},
  {"word": "recognition", "correct": "認識", "choices": ["認識", "対立"], "etymology": "レコグニション（/rˌekʌɡnˈɪʃʌn/）", "example1": "She finally got the recognition she deserved.", "jp1": "彼女はついにそれに値する評価を得た。"},
  {"word": "injury", "correct": "けが", "choices": ["けが", "歴史家"], "etymology": "インジャリー（/ˈɪndʒɝi/）", "example1": "He could not play because of an injury.", "jp1": "彼はけがのためプレーできなかった。"},
  {"word": "justice", "correct": "正義", "choices": ["正義", "文"], "etymology": "ジャスティス（/dʒˈʌstʌs/）", "example1": "They are fighting for justice.", "jp1": "彼らは正義のために戦っている。"},
  {"word": "component", "correct": "構成要素", "choices": ["構成要素", "スタジオ"], "etymology": "コンポーネント（/kʌmpˈoʊnʌnt/）", "example1": "This machine has many small components.", "jp1": "その機械には多くの小さな部品がある。"}
];
