window.quizData = [
  {"word": "condition", "correct": "状態", "choices": ["状態", "信用"], "etymology": "コンディション（kʌndˈɪʃʌn）", "example1": "The patient is in stable condition.", "jp1": "その患者は安定した状態にある。"},
  {"word": "inflation", "correct": "インフレ", "choices": ["インフレ", "信号"], "etymology": "インフレーション（ˌɪnflˈeɪʃʌn）", "example1": "Inflation increased food prices.", "jp1": "インフレで食料品の価格が上がった。"},
  {"word": "instructor", "correct": "指導者", "choices": ["指導者", "前進"], "etymology": "インストラクター（ˌɪnstrˈʌktɝ）", "example1": "The instructor explained the rules.", "jp1": "その指導者は規則を説明した。"},
  {"word": "destination", "correct": "目的地", "choices": ["目的地", "移転"], "etymology": "デスティネーション（dˌestʌnˈeɪʃʌn）", "example1": "Tokyo was our final destination.", "jp1": "東京が私たちの最終目的地だった。"},
  {"word": "foundation", "correct": "基礎", "choices": ["基礎", "需要"], "etymology": "ファウンデーション（faʊndˈeɪʃʌn）", "example1": "Trust is the foundation of friendship.", "jp1": "信頼は友情の土台だ。"},
  {"word": "connection", "correct": "つながり", "choices": ["つながり", "輸出"], "etymology": "コネクション（kʌnˈekʃʌn）", "example1": "There is a close connection between diet and health.", "jp1": "食事と健康には密接な関係がある。"},
  {"word": "reaction", "correct": "反応", "choices": ["反応", "保証"], "etymology": "リアクション（riˈækʃʌn）", "example1": "Her reaction was unexpected.", "jp1": "彼女の反応は予想外だった。"},
  {"word": "vehicle", "correct": "乗り物", "choices": ["乗り物", "子ども時代"], "etymology": "ビークル（vˈihɪkʌl）", "example1": "Electric vehicles are becoming more common.", "jp1": "電気自動車はますます一般的になっている。"},
  {"word": "presence", "correct": "存在", "choices": ["存在", "定義"], "etymology": "プレゼンス（prˈezʌns）", "example1": "Her presence made everyone feel calm.", "jp1": "彼女がいるとみんなが落ち着いた。"},
  {"word": "judgment", "correct": "判断", "choices": ["判断", "論争"], "etymology": "ジャッジメント（dʒˈʌdʒmʌnt）", "example1": "Use your own judgment.", "jp1": "自分自身の判断を使いなさい。"},
  {"word": "engine", "correct": "エンジン", "choices": ["エンジン", "表現"], "etymology": "エンジン（ˈendʒʌn）", "example1": "The engine makes a strange noise.", "jp1": "そのエンジンは変な音を立てている。"},
  {"word": "evidence", "correct": "証拠", "choices": ["証拠", "選択肢"], "etymology": "エビデンス（ˈevʌdʌns）", "example1": "There is little evidence to support the claim.", "jp1": "その主張を裏づける証拠はほとんどない。"},
  {"word": "protection", "correct": "保護", "choices": ["保護", "大多数"], "etymology": "プロテクション（prʌtˈekʃʌn）", "example1": "Sunscreen gives protection from the sun.", "jp1": "日焼け止めは太陽から肌を守ってくれる。"},
  {"word": "identity", "correct": "正体", "choices": ["正体", "重さ"], "etymology": "アイデンティティ（aɪdˈentɪtˌi）", "example1": "The police checked his identity.", "jp1": "警察は彼の身元を確認した。"},
  {"word": "context", "correct": "文脈", "choices": ["文脈", "職場"], "etymology": "コンテクスト（kˈɑntekst）", "example1": "The meaning changes depending on the context.", "jp1": "意味は文脈によって変わる。"},
  {"word": "construction", "correct": "建設", "choices": ["建設", "変化"], "etymology": "コンストラクション（kʌnstrˈʌkʃʌn）", "example1": "Construction of the bridge began in April.", "jp1": "その橋の建設は4月に始まった。"},
  {"word": "capacity", "correct": "能力", "choices": ["能力", "少数派"], "etymology": "キャパシティ（kʌpˈæsʌti）", "example1": "The hall has a capacity of 500 people.", "jp1": "そのホールの収容人数は500人だ。"},
  {"word": "session", "correct": "会期", "choices": ["会期", "福祉"], "etymology": "セッション（sˈeʃʌn）", "example1": "The morning session starts at nine.", "jp1": "午前の部は9時に始まる。"},
  {"word": "civilization", "correct": "文明", "choices": ["文明", "展示会"], "etymology": "シビライゼーション（sˌɪvʌlɪzˈeɪʃʌn）", "example1": "Ancient civilization left many ruins.", "jp1": "古代文明は多くの遺跡を残した。"},
  {"word": "belief", "correct": "信念", "choices": ["信念", "交渉"], "etymology": "ビリーフ（bɪlˈif）", "example1": "That belief is common in the area.", "jp1": "その信念はその地域では一般的だ。"},
  {"word": "finding", "correct": "発見", "choices": ["発見", "議会"], "etymology": "ファインディング（fˈaɪndɪŋ）", "example1": "The findings were surprising.", "jp1": "その調査結果は驚くべきものだった。"},
  {"word": "invest", "correct": "投資", "choices": ["投資", "代用品"], "etymology": "インベスト（ˌɪnvˈest）", "example1": "The noun use of invest is rare.", "jp1": "invest の名詞用法はまれだ。"},
  {"word": "conduct", "correct": "行為", "choices": ["行為", "見知らぬ人"], "etymology": "コンダクト（kˈɑndʌkt）", "example1": "His conduct was appropriate.", "jp1": "彼の行為は適切だった。"},
  {"word": "analyst", "correct": "分析家", "choices": ["分析家", "反対"], "etymology": "アナリスト（ˈænʌlɪst）", "example1": "An analyst explained the trend.", "jp1": "ある分析家がその傾向を説明した。"},
  {"word": "shadow", "correct": "影", "choices": ["影", "地区"], "etymology": "シャドー（ʃˈædˌoʊ）", "example1": "The tree cast a long shadow.", "jp1": "その木は長い影を落とした。"},
  {"word": "licence", "correct": "免許", "choices": ["免許", "発明"], "etymology": "ライセンス（lˈaɪsʌns）", "example1": "You need a licence to drive here.", "jp1": "ここでは運転に免許が必要だ。"},
  {"word": "absence", "correct": "欠席", "choices": ["欠席", "指導力"], "etymology": "アブセンス（ˈæbsʌns）", "example1": "His absence was noticed.", "jp1": "彼の欠席は気づかれていた。"},
  {"word": "technique", "correct": "技術", "choices": ["技術", "割合"], "etymology": "テクニーク（teknˈik）", "example1": "This cooking technique is simple.", "jp1": "この料理の技法は簡単だ。"},
  {"word": "delivery", "correct": "配達", "choices": ["配達", "例外"], "etymology": "デリバリー（dɪlˈɪvɝi）", "example1": "The delivery arrived on time.", "jp1": "配達は時間どおりに届いた。"},
  {"word": "deadline", "correct": "締め切り", "choices": ["締め切り", "侮辱"], "etymology": "デッドライン（ˈdɛdˌlaɪn）", "example1": "The deadline is next Friday.", "jp1": "締め切りは来週の金曜日だ。"},
  {"word": "employee", "correct": "従業員", "choices": ["従業員", "購入"], "etymology": "エンプロイイー（emplˈɔɪi）", "example1": "Every employee must wear an ID card.", "jp1": "すべての従業員は身分証を身につけなければならない。"},
  {"word": "concern", "correct": "懸念", "choices": ["懸念", "装置"], "etymology": "コンサーン（kʌnsˈɝn）", "example1": "Safety is my main concern.", "jp1": "安全が私の最大の懸念だ。"},
  {"word": "humidity", "correct": "湿度", "choices": ["湿度", "緊張"], "etymology": "ヒューミディティ（hjumˈɪdʌti）", "example1": "Humidity is high in summer.", "jp1": "夏は湿度が高い。"},
  {"word": "target", "correct": "目標", "choices": ["目標", "概念"], "etymology": "ターゲット（tˈɑrɡʌt）", "example1": "Our sales target is ambitious.", "jp1": "私たちの売上目標は高い。"},
  {"word": "release", "correct": "公開", "choices": ["公開", "脅威"], "etymology": "リリース（rilˈis）", "example1": "The film's release was delayed.", "jp1": "その映画の公開は延期された。"},
  {"word": "output", "correct": "生産高", "choices": ["生産高", "暴力"], "etymology": "アウトプット（ˈaʊtˌpʊt）", "example1": "Factory output increased last month.", "jp1": "工場の生産高は先月増えた。"},
  {"word": "monitor", "correct": "監視装置", "choices": ["監視装置", "経路"], "etymology": "モニター（mˈɑnʌtɝ）", "example1": "The patient was connected to a heart monitor.", "jp1": "その患者は心拍モニターにつながれていた。"},
  {"word": "finance", "correct": "財政", "choices": ["財政", "省庁"], "etymology": "ファイナンス（fʌnˈæns）", "example1": "She works in finance.", "jp1": "彼女は財務部門で働いている。"},
  {"word": "progress", "correct": "進歩", "choices": ["進歩", "ネットワーク"], "etymology": "プログレス（prˈɑɡrˌes）", "example1": "The project is making progress.", "jp1": "その計画は進展している。"},
  {"word": "appeal", "correct": "魅力", "choices": ["魅力", "教授"], "etymology": "アピール（ʌpˈil）", "example1": "The idea has wide appeal.", "jp1": "その考えには広い魅力がある。"},
  {"word": "review", "correct": "再検討", "choices": ["再検討", "利点"], "etymology": "レビュー（rˌivjˈu）", "example1": "The teacher wrote a review of the essay.", "jp1": "先生はその作文について講評を書いた。"},
  {"word": "charge", "correct": "料金", "choices": ["料金", "農業"], "etymology": "チャージ（tʃˈɑrdʒ）", "example1": "There is no extra charge.", "jp1": "追加料金はかからない。"},
  {"word": "measure", "correct": "措置", "choices": ["措置", "解釈"], "etymology": "メジャー（mˈeʒɝ）", "example1": "The government announced new measures.", "jp1": "政府は新しい対策を発表した。"},
  {"word": "handle", "correct": "取っ手", "choices": ["取っ手", "医療"], "etymology": "ハンドル（hˈændʌl）", "example1": "The cup has a broken handle.", "jp1": "そのカップの取っ手は壊れている。"},
  {"word": "desire", "correct": "願望", "choices": ["願望", "行動"], "etymology": "ディザイア（dɪzˈaɪɝ）", "example1": "He had a strong desire to win.", "jp1": "彼には勝ちたいという強い願望があった。"},
  {"word": "record", "correct": "記録", "choices": ["記録", "違反"], "etymology": "レコード（rʌkˈɔrd）", "example1": "She holds the school record.", "jp1": "彼女は学校記録を持っている。"},
  {"word": "account", "correct": "説明", "choices": ["説明", "含意"], "etymology": "アカウント（ʌkˈaʊnt）", "example1": "His account of the event was detailed and clear.", "jp1": "彼のその出来事についての説明は詳しくてわかりやすかった。"},
  {"word": "battle", "correct": "戦い", "choices": ["戦い", "年金"], "etymology": "バトル（bˈætʌl）", "example1": "The battle changed history.", "jp1": "その戦いは歴史を変えた。"},
  {"word": "silence", "correct": "沈黙", "choices": ["沈黙", "運動"], "etymology": "サイレンス（sˈaɪlʌns）", "example1": "The room fell into silence.", "jp1": "部屋は静まり返った。"},
  {"word": "launch", "correct": "開始", "choices": ["開始", "重要性"], "etymology": "ローンチ（lˈɔntʃ）", "example1": "The launch of the product was successful.", "jp1": "その製品の発売は成功した。"},
  {"word": "direct", "correct": "演出", "choices": ["演出", "地位"], "etymology": "ダイレクト（dɝˈekt）", "example1": "The noun use of direct is rare.", "jp1": "direct の名詞用法はまれだ。"},
  {"word": "respect", "correct": "敬意", "choices": ["敬意", "類似"], "etymology": "リスペクト（rɪspˈekt）", "example1": "Children should show respect for others.", "jp1": "子どもは他人に敬意を示すべきだ。"},
  {"word": "contrast", "correct": "対比", "choices": ["対比", "質"], "etymology": "コントラスト（kˈɑntræst）", "example1": "The contrast between the two pictures is clear.", "jp1": "その2枚の絵の対比は明らかだ。"},
  {"word": "debate", "correct": "討論", "choices": ["討論", "注意喚起"], "etymology": "ディベート（dʌbˈeɪt）", "example1": "The debate lasted two hours.", "jp1": "その討論は2時間続いた。"},
  {"word": "treat", "correct": "ごちそう", "choices": ["ごちそう", "発展"], "etymology": "トリート（trˈit）", "example1": "This cake is a sweet treat.", "jp1": "このケーキは甘いごちそうだ。"},
  {"word": "approach", "correct": "方法", "choices": ["方法", "基準"], "etymology": "アプローチ（ʌprˈoʊtʃ）", "example1": "We need a different approach.", "jp1": "私たちには別の取り組み方が必要だ。"},
  {"word": "reserve", "correct": "蓄え", "choices": ["蓄え", "手術"], "etymology": "リザーブ（rɪzˈɝv）", "example1": "The animal lives on a nature reserve.", "jp1": "その動物は自然保護区に住んでいる。"},
  {"word": "object", "correct": "物体", "choices": ["物体", "通貨"], "etymology": "オブジェクト（ˈɑbdʒekt）", "example1": "The object is made of glass.", "jp1": "その物体はガラス製だ。"},
  {"word": "doubt", "correct": "疑い", "choices": ["疑い", "強調"], "etymology": "ダウト（dˈaʊt）", "example1": "I have no doubt about that.", "jp1": "私はそれについて疑いを持っていない。"},
  {"word": "award", "correct": "賞", "choices": ["賞", "監督"], "etymology": "アワード（ʌwˈɔrd）", "example1": "She won an award for her research.", "jp1": "彼女は研究で賞を受けた。"},
  {"word": "challenge", "correct": "難題", "choices": ["難題", "材料"], "etymology": "チャレンジ（tʃˈælʌndʒ）", "example1": "Learning a language is a challenge.", "jp1": "言語を学ぶことは難題だ。"},
  {"word": "murder", "correct": "殺人", "choices": ["殺人", "設備"], "etymology": "マーダー（mˈɝdɝ）", "example1": "The police investigated the murder.", "jp1": "警察はその殺人事件を調査した。"},
  {"word": "branch", "correct": "支部", "choices": ["支部", "展望"], "etymology": "ブランチ（brˈæntʃ）", "example1": "The bank opened a new branch.", "jp1": "その銀行は新しい支店を開いた。"},
  {"word": "supply", "correct": "供給", "choices": ["供給", "共和国"], "etymology": "サプライ（sʌplˈaɪ）", "example1": "The water supply was cut off.", "jp1": "水の供給が止まった。"},
  {"word": "shape", "correct": "形", "choices": ["形", "文書"], "etymology": "シェイプ（ʃˈeɪp）", "example1": "The table is oval in shape.", "jp1": "そのテーブルは形が楕円だ。"},
  {"word": "shock", "correct": "衝撃", "choices": ["衝撃", "郡"], "etymology": "ショック（ʃˈɑk）", "example1": "The news gave us a shock.", "jp1": "その知らせは私たちに衝撃を与えた。"},
  {"word": "protest", "correct": "抗議", "choices": ["抗議", "4分の1"], "etymology": "プロテスト（prˈoʊtˌest）", "example1": "There was a protest in front of city hall.", "jp1": "市役所の前で抗議活動があった。"},
  {"word": "upgrade", "correct": "向上", "choices": ["向上", "事務弁護士"], "etymology": "アップグレード（ˈʌpˌɡreɪd）", "example1": "The hotel room upgrade was free.", "jp1": "そのホテルの部屋のアップグレードは無料だった。"},
  {"word": "search", "correct": "捜索", "choices": ["捜索", "法律"], "etymology": "サーチ（sˈɝtʃ）", "example1": "The search for the missing hiker continued.", "jp1": "行方不明のハイカーの捜索は続いた。"},
  {"word": "attempt", "correct": "試み", "choices": ["試み", "民主主義"], "etymology": "アテンプト（ʌtˈempt）", "example1": "This was his first attempt.", "jp1": "これは彼の最初の試みだった。"},
  {"word": "display", "correct": "展示", "choices": ["展示", "版"], "etymology": "ディスプレイ（dɪsplˈeɪ）", "example1": "The museum has a display of ancient tools.", "jp1": "その博物館には古代の道具の展示がある。"},
  {"word": "gain", "correct": "利益", "choices": ["利益", "失敗"], "etymology": "ゲイン（ɡˈeɪn）", "example1": "The company reported a large gain.", "jp1": "その会社は大きな利益を報告した。"},
  {"word": "matter", "correct": "事柄", "choices": ["事柄", "使用人"], "etymology": "マター（mˈætɝ）", "example1": "This is a serious matter.", "jp1": "これは重大な問題だ。"},
  {"word": "credit", "correct": "信用", "choices": ["信用", "保有者"], "etymology": "クレジット（krˈedʌt）", "example1": "She deserves credit for the success.", "jp1": "その成功については彼女が評価されるべきだ。"},
  {"word": "signal", "correct": "信号", "choices": ["信号", "部類"], "etymology": "シグナル（sˈɪɡnʌl）", "example1": "The signal turned red.", "jp1": "信号が赤に変わった。"},
  {"word": "advance", "correct": "前進", "choices": ["前進", "近所の人"], "etymology": "アドバンス（ʌdvˈæns）", "example1": "The advance in technology was remarkable.", "jp1": "科学技術の進歩は目覚ましかった。"},
  {"word": "transfer", "correct": "移転", "choices": ["移転", "息"], "etymology": "トランスファー（trænsfˈɝ）", "example1": "The transfer took only a minute.", "jp1": "その送金には1分しかかからなかった。"},
  {"word": "demand", "correct": "需要", "choices": ["需要", "必要条件"], "etymology": "ディマンド（dɪmˈænd）", "example1": "There is strong demand for cheap housing.", "jp1": "安い住宅には強い需要がある。"},
  {"word": "export", "correct": "輸出", "choices": ["輸出", "大統領"], "etymology": "エクスポート（ˈekspɔrt）", "example1": "Rice is an important export here.", "jp1": "米はこの地域の重要な輸出品だ。"},
  {"word": "guarantee", "correct": "保証", "choices": ["保証", "提案"], "etymology": "ギャランティ（ɡˌerʌntˈi）", "example1": "This watch comes with a two-year guarantee.", "jp1": "この時計には2年保証が付いている。"}
];
