window.quizData = [
  {"word":"establish","correct":"を設立する","choices":["を設立する","を保持する"],"etymology":"イスターブリッシュ（ɪstˈæblɪʃ）","example1":"The company established a new office in Osaka.","jp1":"その会社は大阪に新しい支社を設立した。"},
  {"word":"retire","correct":"退職する","choices":["退職する","を雇う"],"etymology":"リタイア（rɪtˈaɪr）","example1":"My father retired at the age of sixty-five.","jp1":"父は65歳で退職した。"},
  {"word":"occupy","correct":"を占める","choices":["を占める","を払い戻す"],"etymology":"アーキュパイ（ˈɑkjʌpˌaɪ）","example1":"The sofa occupies too much space in the room.","jp1":"そのソファーは部屋の中で場所を取りすぎている。"},
  {"word":"recall","correct":"を思い出す","choices":["を思い出す","に言及する"],"etymology":"リコール（rˈikˌɔl）","example1":"I can clearly recall that day.","jp1":"私はその日をはっきりと思い出すことができる。"},
  {"word":"contribute","correct":"貢献する","choices":["貢献する","を調べる"],"etymology":"コントリビュート（kʌntrˈɪbjut）","example1":"Many volunteers contributed to the project.","jp1":"多くのボランティアがその計画に貢献した。"},
  {"word":"appreciate","correct":"を感謝する","choices":["を感謝する","を受け継ぐ"],"etymology":"アプリシエイト（ʌprˈiʃiˌeɪt）","example1":"I really appreciate your help.","jp1":"私はあなたの助けに本当に感謝している。"},
  {"word":"compensate","correct":"に埋め合わせをする","choices":["に埋め合わせをする","参加する"],"etymology":"カンペンセイト（kˈɑmpʌnsˌeɪt）","example1":"The company compensated workers for the damage.","jp1":"その会社は損害に対して労働者に補償をした。"},
  {"word":"ignore","correct":"を無視する","choices":["を無視する","を暗記する"],"etymology":"イグノア（ˌɪɡnˈɔr）","example1":"He ignored my advice.","jp1":"彼は私の助言を無視した。"},
  {"word":"emerge","correct":"現れる","choices":["現れる","申し込む"],"etymology":"イマージ（ɪmˈɝdʒ）","example1":"New problems emerged after the meeting.","jp1":"会議のあとで新しい問題が生じた。"},
  {"word":"oppose","correct":"に反対する","choices":["に反対する","を生み出す"],"etymology":"オポウズ（ʌpˈoʊz）","example1":"Many people opposed the plan.","jp1":"多くの人がその計画に反対した。"},
  {"word":"investigate","correct":"を調査する","choices":["を調査する","を大きくする"],"etymology":"インベステゲイト（ˌɪnvˈestʌɡˌeɪt）","example1":"Police are investigating the accident.","jp1":"警察はその事故を調査している。"},
  {"word":"absorb","correct":"を吸収する","choices":["を吸収する","を破壊する"],"etymology":"アブゾーブ（ʌbzˈɔrb）","example1":"Plants absorb water through their roots.","jp1":"植物は根を通して水を吸収する。"},
  {"word":"struggle","correct":"奮闘する","choices":["奮闘する","を輸送する"],"etymology":"ストラグル（strˈʌɡʌl）","example1":"She struggled to finish the report on time.","jp1":"彼女は時間までにレポートを終えるのに苦労した。"},
  {"word":"propose","correct":"を提案する","choices":["を提案する","を再利用する"],"etymology":"プロポウズ（prʌpˈoʊz）","example1":"They proposed a new idea.","jp1":"彼らは新しい案を提案した。"},
  {"word":"decline","correct":"減少する","choices":["減少する","を見積もる"],"etymology":"ディクライン（dɪklˈaɪn）","example1":"Sales declined last year.","jp1":"売上は昨年減少した。"},
  {"word":"deny","correct":"を否定する","choices":["を否定する","を救助する"],"etymology":"ディナイ（dɪnˈaɪ）","example1":"He denied the rumor.","jp1":"彼はそのうわさを否定した。"},
  {"word":"recover","correct":"回復する","choices":["回復する","を表現する"],"etymology":"リカバー（rɪkˈʌvɝ）","example1":"She recovered from the illness quickly.","jp1":"彼女はその病気からすぐに回復した。"},
  {"word":"tolerate","correct":"を我慢する","choices":["を我慢する","を得る"],"etymology":"タレレイト（tˈɑlɝˌeɪt）","example1":"I cannot tolerate such rude behavior.","jp1":"私はそのような失礼な行動には耐えられない。"},
  {"word":"insist","correct":"強く主張する","choices":["強く主張する","返答する"],"etymology":"インスィスト（ˌɪnsˈɪst）","example1":"He insisted that he was right.","jp1":"彼は自分が正しいと強く主張した。"},
  {"word":"accomplish","correct":"を成し遂げる","choices":["を成し遂げる","成り立つ"],"etymology":"アカンプリッシュ（ʌkˈɑmplɪʃ）","example1":"She accomplished her goal.","jp1":"彼女は目標を達成した。"},
  {"word":"regret","correct":"を後悔する","choices":["を後悔する","を管理する"],"etymology":"リグレット（rʌɡrˈet）","example1":"I regret my careless mistake.","jp1":"私は自分の不注意なミスを後悔している。"},
  {"word":"detect","correct":"を発見する","choices":["を発見する","を勧める"],"etymology":"ディテクト（dɪtˈekt）","example1":"The machine detected smoke.","jp1":"その機械は煙を検知した。"},
  {"word":"fulfill","correct":"を果たす","choices":["を果たす","に遭遇する"],"etymology":"フルフィル（fʊlfˈɪl）","example1":"He fulfilled his promise.","jp1":"彼は約束を果たした。"},
  {"word":"preserve","correct":"を保存する","choices":["を保存する","を任命する"],"etymology":"プリザーブ（prʌzˈɝv）","example1":"This museum preserves local history.","jp1":"この博物館は地域の歴史を保存している。"},
  {"word":"determine","correct":"を決定する","choices":["を決定する","を悩ませる"],"etymology":"ディターミン（dʌtˈɝmʌn）","example1":"The test will determine the winner.","jp1":"その試験が勝者を決めるだろう。"},
  {"word":"donate","correct":"を寄付する","choices":["を寄付する","を代表する"],"etymology":"ドゥネイト（dˈoʊnˌeɪt）","example1":"Many people donated money to the charity.","jp1":"多くの人がその慈善団体にお金を寄付した。"},
  {"word":"achieve","correct":"を達成する","choices":["を達成する","を身につける"],"etymology":"アチーブ（ʌtʃˈiv）","example1":"She achieved excellent results.","jp1":"彼女はすばらしい結果を達成した。"},
  {"word":"convert","correct":"を変える","choices":["を変える","を鼓舞する"],"etymology":"コンバート（kˈɑnvɝt）","example1":"They converted the old house into a cafe.","jp1":"彼らはその古い家をカフェに変えた。"},
  {"word":"satisfy","correct":"を満たす","choices":["を満たす","を専門とする"],"etymology":"サーティスファイ（sˈætʌsfˌaɪ）","example1":"The product satisfied customer needs.","jp1":"その製品は顧客のニーズを満たした。"},
  {"word":"migrate","correct":"移動する","choices":["移動する","を宣言する"],"etymology":"マイグレイト（mˈaɪɡrˌeɪt）","example1":"Some birds migrate in winter.","jp1":"鳥の中には冬に移動するものもいる。"},
  {"word":"resist","correct":"に抵抗する","choices":["に抵抗する","を促進する"],"etymology":"リジスト（rɪzˈɪst）","example1":"He resisted the temptation to quit.","jp1":"彼はやめたいという誘惑に抵抗した。"},
  {"word":"deserve","correct":"に値する","choices":["に値する","を傷つける"],"etymology":"ディザーブ（dɪzˈɝv）","example1":"You deserve a better chance.","jp1":"あなたにはもっとよい機会に値する。"},
  {"word":"conclude","correct":"と結論づける","choices":["と結論づける","を怖がらせる"],"etymology":"コンクルード（kʌnklˈud）","example1":"We concluded that the plan was risky.","jp1":"私たちはその計画は危険だと結論づけた。"},
  {"word":"select","correct":"を選ぶ","choices":["を選ぶ","を示す"],"etymology":"セレクト（sʌlˈekt）","example1":"Please select the best answer.","jp1":"最もよい答えを選びなさい。"},
  {"word":"analyze","correct":"を分析する","choices":["を分析する","集中する"],"etymology":"アナライズ（ˈænʌlˌaɪz）","example1":"Scientists analyzed the data carefully.","jp1":"科学者たちはそのデータを注意深く分析した。"},
  {"word":"succeed","correct":"成功する","choices":["成功する","を行う"],"etymology":"サクスィード（sʌksˈid）","example1":"He succeeded in solving the problem.","jp1":"彼はその問題を解くことに成功した。"},
  {"word":"retain","correct":"を保持する","choices":["を保持する","を評価する"],"etymology":"リテイン（rɪtˈeɪn）","example1":"The company retained its customers.","jp1":"その会社は顧客をつなぎとめた。"},
  {"word":"employ","correct":"を雇う","choices":["を雇う","を採用する"],"etymology":"エンプロイ（emplˈɔɪ）","example1":"The factory employs many local people.","jp1":"その工場は多くの地元の人を雇っている。"},
  {"word":"refund","correct":"を払い戻す","choices":["を払い戻す","を確認する"],"etymology":"リファンド（rɪfˈʌnd）","example1":"The store refunded my money.","jp1":"その店は私に代金を返金した。"},
  {"word":"mention","correct":"に言及する","choices":["に言及する","生き残る"],"etymology":"メンション（mˈenʃʌn）","example1":"She mentioned the problem in her email.","jp1":"彼女はメールの中でその問題に言及した。"},
  {"word":"impress","correct":"を感動させる","choices":["を感動させる","資格を得る"],"etymology":"インプレス（ˌɪmprˈes）","example1":"His speech impressed the audience.","jp1":"彼のスピーチは聴衆を感動させた。"},
  {"word":"examine","correct":"を調べる","choices":["を調べる","を届ける"],"etymology":"イグザミン（ɪɡzˈæmɪn）","example1":"The doctor examined my eyes.","jp1":"医者は私の目を診察した。"},
  {"word":"inherit","correct":"を受け継ぐ","choices":["を受け継ぐ","を手配する"],"etymology":"インヘリト（ˌɪnhˈerʌt）","example1":"She inherited her grandmother's ring.","jp1":"彼女は祖母の指輪を受け継いだ。"},
  {"word":"participate","correct":"参加する","choices":["参加する","を観察する"],"etymology":"パーティサペイト（pɑrtˈɪsʌpˌeɪt）","example1":"Many students participated in the event.","jp1":"多くの生徒がその行事に参加した。"},
  {"word":"memorize","correct":"を暗記する","choices":["を暗記する","を課す"],"etymology":"メモライズ（mˈemɝˌaɪz）","example1":"Students must memorize these words.","jp1":"生徒たちはこれらの単語を暗記しなければならない。"},
  {"word":"apply","correct":"申し込む","choices":["申し込む","を回復させる"],"etymology":"アプライ（ʌplˈaɪ）","example1":"I applied for the job yesterday.","jp1":"私は昨日その仕事に申し込んだ。"},
  {"word":"generate","correct":"を生み出す","choices":["を生み出す","を拒否する"],"etymology":"ジェネレイト（dʒˈenɝˌeɪt）","example1":"The project generated new ideas.","jp1":"その計画は新しい考えを生み出した。"},
  {"word":"enlarge","correct":"を大きくする","choices":["を大きくする","を克服する"],"etymology":"エンラージ（ˌenlˈɑrdʒ）","example1":"Click here to enlarge the image.","jp1":"画像を大きくするにはここをクリックしてください。"},
  {"word":"destroy","correct":"を破壊する","choices":["を破壊する","反応する"],"etymology":"ディストロイ（dɪstrˈɔɪ）","example1":"The fire destroyed several houses.","jp1":"その火事はいくつかの家を破壊した。"},
  {"word":"transport","correct":"を輸送する","choices":["を輸送する","を維持する"],"etymology":"トランスポート（trænspˈɔrt）","example1":"Trucks transport goods across the country.","jp1":"トラックは全国に商品を輸送する。"},
  {"word":"recycle","correct":"を再利用する","choices":["を再利用する","を予測する"],"etymology":"リサイクウ（risˈaɪkʌl）","example1":"We should recycle more plastic bottles.","jp1":"私たちはもっと多くのプラスチックびんを再利用すべきだ。"},
  {"word":"estimate","correct":"を見積もる","choices":["を見積もる","を操作する"],"etymology":"エスティメイト（ˈestʌmʌt）","example1":"Experts estimated the cost at ten million yen.","jp1":"専門家たちはその費用を1000万円と見積もった。"},
  {"word":"rescue","correct":"を救助する","choices":["を救助する","意思疎通する"],"etymology":"レスキュー（rˈeskju）","example1":"The team rescued the lost child.","jp1":"その隊は迷子の子どもを救助した。"},
  {"word":"express","correct":"を表現する","choices":["を表現する","に知らせる"],"etymology":"イクスプレス（ɪksprˈes）","example1":"He expressed his opinion clearly.","jp1":"彼は自分の意見をはっきりと表現した。"},
  {"word":"obtain","correct":"を得る","choices":["を得る","をほめる"],"etymology":"アブテイン（ʌbtˈeɪn）","example1":"You need a passport to obtain a visa.","jp1":"ビザを取得するにはパスポートが必要だ。"},
  {"word":"respond","correct":"返答する","choices":["返答する","を蓄える"],"etymology":"リスパンド（rɪspˈɑnd）","example1":"He responded to my question politely.","jp1":"彼は私の質問に丁寧に答えた。"},
  {"word":"consist","correct":"成り立つ","choices":["成り立つ","を伴う"],"etymology":"コンスィスト（kʌnsˈɪst）","example1":"The team consists of five members.","jp1":"そのチームは5人で構成されている。"},
  {"word":"manage","correct":"を管理する","choices":["を管理する","を取り付ける"],"etymology":"マネージ（mˈænʌdʒ）","example1":"She manages a small restaurant.","jp1":"彼女は小さなレストランを経営している。"},
  {"word":"recommend","correct":"を勧める","choices":["を勧める","を広げる"],"etymology":"レコメンド（rˌekʌmˈend）","example1":"I recommend this book to beginners.","jp1":"私はこの本を初学者に勧める。"},
  {"word":"encounter","correct":"に遭遇する","choices":["に遭遇する","を喜ばせる"],"etymology":"インカウンター（ɪnkˈaʊntɝ）","example1":"We encountered heavy rain on the way.","jp1":"私たちは途中で激しい雨に遭遇した。"},
  {"word":"appoint","correct":"を任命する","choices":["を任命する","を説明する"],"etymology":"アポイント（ʌpˈɔɪnt）","example1":"They appointed her as the leader.","jp1":"彼らは彼女をリーダーに任命した。"},
  {"word":"bother","correct":"を悩ませる","choices":["を悩ませる","をほのめかす"],"etymology":"バザー（bˈɑðɝ）","example1":"The noise bothered me all night.","jp1":"その騒音が一晩中私を悩ませた。"},
  {"word":"represent","correct":"を代表する","choices":["を代表する","を消費する"],"etymology":"レプリゼント（rˌeprɪzˈent）","example1":"This painting represents peace.","jp1":"この絵は平和を表している。"},
  {"word":"acquire","correct":"を身につける","choices":["を身につける","を動揺させる"],"etymology":"アクワイア（ʌkwˈaɪɝ）","example1":"Children acquire language naturally.","jp1":"子どもは自然に言語を身につける。"},
  {"word":"inspire","correct":"を鼓舞する","choices":["を鼓舞する","を宣伝する"],"etymology":"インスパイア（ˌɪnspˈaɪr）","example1":"Her story inspired many people.","jp1":"彼女の話は多くの人を鼓舞した。"},
  {"word":"specialize","correct":"を専門とする","choices":["を専門とする","を再建する"],"etymology":"スペシャライズ（spˈeʃʌlˌaɪz）","example1":"He specializes in environmental law.","jp1":"彼は環境法を専門としている。"},
  {"word":"declare","correct":"を宣言する","choices":["を宣言する","謝る"],"etymology":"ディクレア（dɪklˈer）","example1":"The mayor declared the event open.","jp1":"市長はその行事の開始を宣言した。"},
  {"word":"promote","correct":"を促進する","choices":["を促進する","進化する"],"etymology":"プロモウト（prʌmˈoʊt）","example1":"The campaign promotes healthy eating.","jp1":"その運動は健康的な食事を促進している。"},
  {"word":"injure","correct":"を傷つける","choices":["を傷つける","を妨げる"],"etymology":"インジャー（ˈɪndʒɝ）","example1":"The accident injured two people.","jp1":"その事故で2人がけがをした。"},
  {"word":"scare","correct":"を怖がらせる","choices":["を怖がらせる","と結婚する"],"etymology":"スケア（skˈer）","example1":"The loud sound scared the dog.","jp1":"その大きな音が犬を怖がらせた。"},
  {"word":"indicate","correct":"を示す","choices":["を示す","適応する"],"etymology":"インディケイト（ˈɪndʌkˌeɪt）","example1":"The sign indicates the exit.","jp1":"その標識は出口を示している。"},
  {"word":"concentrate","correct":"集中する","choices":["集中する","を組織する"],"etymology":"コンセントレイト（kˈɑnsʌntrˌeɪt）","example1":"Please concentrate on your work.","jp1":"自分の仕事に集中しなさい。"},
  {"word":"perform","correct":"を行う","choices":["を行う","を告白する"],"etymology":"パフォーム（pɝfˈɔrm）","example1":"The singer performed three songs.","jp1":"その歌手は3曲を披露した。"},
  {"word":"assess","correct":"を評価する","choices":["を評価する","を特定する"],"etymology":"アセス（ʌsˈes）","example1":"Teachers assess students in different ways.","jp1":"教師たちはさまざまな方法で生徒を評価する。"},
  {"word":"adopt","correct":"を採用する","choices":["を採用する","を打ち負かす"],"etymology":"アダープト（ʌdˈɑpt）","example1":"The city adopted a new policy.","jp1":"その市は新しい方針を採用した。"},
  {"word":"confirm","correct":"を確認する","choices":["を確認する","を繰り返す"],"etymology":"カンファーム（kʌnfˈɝm）","example1":"Please confirm your reservation by email.","jp1":"メールで予約を確認してください。"},
  {"word":"survive","correct":"生き残る","choices":["生き残る","を定義する"],"etymology":"サバイブ（sɝvˈaɪv）","example1":"Few plants can survive in this heat.","jp1":"この暑さの中で生き残れる植物は少ない。"},
  {"word":"qualify","correct":"資格を得る","choices":["資格を得る","を買う余裕がある"],"etymology":"クオリファイ（kwˈɑlʌfˌaɪ）","example1":"She qualified for the final round.","jp1":"彼女は決勝戦への出場資格を得た。"},
  {"word":"deliver","correct":"を届ける","choices":["を届ける","を実証する"],"etymology":"ディリバー（dɪlˈɪvɝ）","example1":"They delivered the package this morning.","jp1":"彼らは今朝その荷物を配達した。"}
];
