window.quizData = [
  {"word": "produce", "correct": "生み出す", "choices": ["生み出す", "意図する"], "etymology": "pro = 前へ + duce = 導く", "example1": "The farm produces organic vegetables.", "jp1": "その農場は有機野菜を生産している。"},
  {"word": "educate", "correct": "教育する", "choices": ["教育する", "変える"], "etymology": "e = 外へ + duc = 導く", "example1": "Schools should educate children to think critically.", "jp1": "学校は子どもたちに批判的に考える力を育てるべきだ。"},
  {"word": "inject", "correct": "注入する", "choices": ["注入する", "逆転する"], "etymology": "in = 中へ + ject = 投げる", "example1": "The nurse injected the medicine slowly.", "jp1": "看護師はゆっくり薬を注射した。"},
  {"word": "reject", "correct": "拒絶する", "choices": ["拒絶する", "含む"], "etymology": "re = 後ろへ + ject = 投げる", "example1": "The committee rejected the proposal.", "jp1": "委員会はその提案を却下した。"},
  {"word": "project", "correct": "投影する", "choices": ["投影する", "除外する"], "etymology": "pro = 前へ + ject = 投げる", "example1": "They plan to project the image onto the wall.", "jp1": "彼らはその画像を壁に映し出すつもりだ。"},
  {"word": "object", "correct": "反対する", "choices": ["反対する", "結論づける"], "etymology": "ob = 向かって + ject = 投げる", "example1": "I object to that idea.", "jp1": "私はその考えに反対だ。"},
  {"word": "attract", "correct": "引きつける", "choices": ["引きつける", "隔離する"], "etymology": "at = 〜へ + tract = 引く", "example1": "Flowers attract bees.", "jp1": "花は蜂を引き寄せる。"},
  {"word": "extract", "correct": "抜き出す", "choices": ["抜き出す", "噴出する"], "etymology": "ex = 外へ + tract = 引く", "example1": "The machine can extract juice from oranges.", "jp1": "その機械はオレンジから果汁を取り出せる。"},
  {"word": "distract", "correct": "注意をそらす", "choices": ["注意をそらす", "適用する"], "etymology": "dis = 離れて + tract = 引く", "example1": "Loud music distracts me from studying.", "jp1": "大きな音楽は勉強の気を散らす。"},
  {"word": "press", "correct": "押す", "choices": ["押す", "暗に示す"], "etymology": "press = 押す", "example1": "Press the red button.", "jp1": "赤いボタンを押してください。"},
  {"word": "compress", "correct": "圧縮する", "choices": ["圧縮する", "返答する"], "etymology": "com = 共に + press = 押す", "example1": "The file was compressed to save space.", "jp1": "そのファイルは容量を節約するために圧縮された。"},
  {"word": "depress", "correct": "落ち込ませる", "choices": ["落ち込ませる", "受け取る"], "etymology": "de = 下へ + press = 押す", "example1": "The news depressed him.", "jp1": "その知らせで彼は落ち込んだ。"},
  {"word": "proceed", "correct": "進む", "choices": ["進む", "受け入れる"], "etymology": "pro = 前へ + ceed = 行く", "example1": "Please proceed to the next room.", "jp1": "次の部屋へお進みください。"},
  {"word": "exceed", "correct": "超える", "choices": ["超える", "預ける"], "etymology": "ex = 外へ + ceed = 行く", "example1": "Do not exceed the speed limit.", "jp1": "制限速度を超えてはいけない。"},
  {"word": "graduate", "correct": "卒業する", "choices": ["卒業する", "延期する"], "etymology": "grad = 歩く・段階", "example1": "She will graduate next spring.", "jp1": "彼女は来年の春に卒業する。"},
  {"word": "extend", "correct": "広げる", "choices": ["広げる", "提案する"], "etymology": "ex = 外へ + tend = 伸ばす", "example1": "We decided to extend the deadline.", "jp1": "私たちは締め切りを延ばすことに決めた。"},
  {"word": "intend", "correct": "意図する", "choices": ["意図する", "調べる"], "etymology": "in = 〜へ + tend = 向ける", "example1": "I intend to study abroad.", "jp1": "私は留学するつもりだ。"},
  {"word": "convert", "correct": "変える", "choices": ["変える", "尊敬する"], "etymology": "con = 共に + vert = 向きを変える", "example1": "They converted the room into a studio.", "jp1": "彼らはその古い家をカフェに変えた。"},
  {"word": "reverse", "correct": "逆転する", "choices": ["逆転する", "命じる"], "etymology": "re = 後ろへ + verse = 向く", "example1": "Please reverse the order.", "jp1": "順番を逆にしてください。"},
  {"word": "include", "correct": "含む", "choices": ["含む", "予測する"], "etymology": "in = 中に + clud = 閉じる", "example1": "The price includes tax.", "jp1": "その価格には税が含まれている。"},
  {"word": "exclude", "correct": "除外する", "choices": ["除外する", "呼び起こす"], "etymology": "ex = 外へ + clud = 閉じる", "example1": "This ticket excludes dinner.", "jp1": "このチケットには夕食は含まれない。"},
  {"word": "conclude", "correct": "結論づける", "choices": ["結論づける", "取り消す"], "etymology": "con = 共に + clud = 閉じる", "example1": "We concluded that the plan was risky.", "jp1": "私たちはその計画は危険だと結論づけた。"},
  {"word": "interrupt", "correct": "中断する", "choices": ["中断する", "購読する"], "etymology": "inter = 間に + rupt = 壊す", "example1": "Do not interrupt me.", "jp1": "私の話をさえぎらないでください。"},
  {"word": "erupt", "correct": "噴出する", "choices": ["噴出する", "処方する"], "etymology": "e = 外へ + rupt = 破る", "example1": "The volcano may erupt again.", "jp1": "その火山は再び噴火するかもしれない。"},
  {"word": "apply", "correct": "適用する", "choices": ["適用する", "サインする"], "etymology": "ap = 〜へ + ply = 重ねる・折る", "example1": "Apply the cream twice a day.", "jp1": "そのクリームを1日に2回塗りなさい。"},
  {"word": "imply", "correct": "暗に示す", "choices": ["暗に示す", "電報を送る"], "etymology": "im = 中へ + ply = 折り込む", "example1": "His silence implied agreement.", "jp1": "彼の沈黙は同意を暗示していた。"},
  {"word": "reply", "correct": "返答する", "choices": ["返答する", "起こる"], "etymology": "re = 戻して + ply = 折る・重ねる", "example1": "She replied at once.", "jp1": "彼女はすぐに返事をした。"},
  {"word": "receive", "correct": "受け取る", "choices": ["受け取る", "追い出す"], "etymology": "re = 戻して + ceive = 受け取る", "example1": "Did you receive my message?", "jp1": "私のメッセージを受け取りましたか。"},
  {"word": "accept", "correct": "受け入れる", "choices": ["受け入れる", "はね返す"], "etymology": "ac = 〜へ + cept = 受け取る", "example1": "He accepted the offer.", "jp1": "彼はその申し出を受け入れた。"},
  {"word": "deposit", "correct": "預ける", "choices": ["預ける", "強く主張する"], "etymology": "de = 下に + posit = 置く", "example1": "Please deposit the money today.", "jp1": "今日そのお金を預けてください。"},
  {"word": "postpone", "correct": "延期する", "choices": ["延期する", "回転する"], "etymology": "post = 後に + pone = 置く", "example1": "We had to postpone the match.", "jp1": "私たちは試合を延期しなければならなかった。"},
  {"word": "propose", "correct": "提案する", "choices": ["提案する", "含む"], "etymology": "pro = 前へ + pose = 置く", "example1": "They proposed a new law.", "jp1": "彼らは新しい案を提案した。"},
  {"word": "inspect", "correct": "調べる", "choices": ["調べる", "進化する"], "etymology": "in = 中まで + spect = 見る", "example1": "The officer inspected the building.", "jp1": "係官はその建物を検査した。"},
  {"word": "respect", "correct": "尊敬する", "choices": ["尊敬する", "一時停止する"], "etymology": "re = 振り返って + spect = 見る", "example1": "We should respect other cultures.", "jp1": "私たちは他の文化を尊重すべきだ。"},
  {"word": "dictate", "correct": "命じる", "choices": ["命じる", "促進する"], "etymology": "dict = 言う", "example1": "Do not let fear dictate your actions.", "jp1": "恐怖に行動を左右されてはいけない。"},
  {"word": "predict", "correct": "予測する", "choices": ["予測する", "溶ける"], "etymology": "pre = 前に + dict = 言う", "example1": "Nobody can predict the future.", "jp1": "未来を予測できる人はいない。"},
  {"word": "describe", "correct": "描写する", "choices": ["描写する", "定義する"], "etymology": "de = 詳しく + scribe = 書く", "example1": "Can you describe the man?", "jp1": "その男の特徴を説明できますか。"},
  {"word": "subscribe", "correct": "購読する", "choices": ["購読する", "耐える"], "etymology": "sub = 下に + scribe = 書く", "example1": "I subscribe to that magazine.", "jp1": "私はその雑誌を定期購読している。"},
  {"word": "prescribe", "correct": "処方する", "choices": ["処方する", "適応する"], "etymology": "pre = 前もって + scribe = 書く", "example1": "The doctor prescribed some medicine.", "jp1": "医者はいくつか薬を処方した。"},
  {"word": "autograph", "correct": "サインする", "choices": ["サインする", "認識する"], "etymology": "auto = 自己 + graph = 書く", "example1": "The player signed an autograph for the boy.", "jp1": "その選手は少年のためにサインを書いた。"},
  {"word": "telegraph", "correct": "電報を送る", "choices": ["電報を送る", "判断する"], "etymology": "tele = 遠く + graph = 書く", "example1": "They telegraphed the news overseas.", "jp1": "彼らはその知らせを海外へ電報で送った。"},
  {"word": "occur", "correct": "起こる", "choices": ["起こる", "設計する"], "etymology": "ob = 向かって + cur = 走る", "example1": "The idea occurred to me later.", "jp1": "その考えはあとで私に思い浮かんだ。"},
  {"word": "expel", "correct": "追い出す", "choices": ["追い出す", "書き留める"], "etymology": "ex = 外へ + pel = 押す", "example1": "The school expelled the student.", "jp1": "学校はその生徒を退学にした。"},
  {"word": "repel", "correct": "はね返す", "choices": ["はね返す", "気づく"], "etymology": "re = 後ろへ + pel = 押す", "example1": "This spray repels insects.", "jp1": "このスプレーは虫を寄せつけない。"},
  {"word": "insist", "correct": "強く主張する", "choices": ["強く主張する", "確かめる"], "etymology": "in = 上に + sist = 立つ", "example1": "She insisted on paying.", "jp1": "彼女は支払うと言い張った。"},
  {"word": "revolve", "correct": "回転する", "choices": ["回転する", "確認する"], "etymology": "re = 再び + volv = 回る", "example1": "The Earth revolves around the sun.", "jp1": "地球は太陽の周りを回る。"},
  {"word": "involve", "correct": "含む", "choices": ["含む", "断言する"], "etymology": "in = 中へ + volv = 巻く", "example1": "The job involves working at night.", "jp1": "その仕事は夜に働くことを伴う。"},
  {"word": "evolve", "correct": "進化する", "choices": ["進化する", "偽造する"], "etymology": "e = 外へ + volv = 巻く", "example1": "Language evolves over time.", "jp1": "言語は時とともに進化する。"},
  {"word": "suspend", "correct": "一時停止する", "choices": ["一時停止する", "生き残る"], "etymology": "sus = 下から + pend = ぶら下げる", "example1": "The train service was suspended.", "jp1": "列車の運行は停止された。"},
  {"word": "promote", "correct": "促進する", "choices": ["促進する", "生き返らせる"], "etymology": "pro = 前へ + mot = 動かす", "example1": "The campaign promotes healthy eating.", "jp1": "その運動は健康的な食事を促進している。"},
  {"word": "dissolve", "correct": "溶ける", "choices": ["溶ける", "活気づける"], "etymology": "dis = 離して + solve = ゆるめる", "example1": "Sugar dissolves in hot water.", "jp1": "砂糖は熱い水に溶ける。"},
  {"word": "resolve", "correct": "解決する", "choices": ["解決する", "鼓舞する"], "etymology": "re = 再び + solve = ゆるめる", "example1": "We must resolve this problem soon.", "jp1": "私たちはこの問題をすぐに解決しなければならない。"},
  {"word": "recruit", "correct": "募集する", "choices": ["募集する", "期限が切れる"], "etymology": "re = 新たに + cret = 成長させる", "example1": "The company recruited new staff.", "jp1": "その会社は新しい職員を採用した。"},
  {"word": "define", "correct": "定義する", "choices": ["定義する", "操作する"], "etymology": "de = はっきり + fin = 境界", "example1": "It is hard to define happiness.", "jp1": "幸福を定義するのは難しい。"},
  {"word": "endure", "correct": "耐える", "choices": ["耐える", "妨げる"], "etymology": "en = 中で + dure = 続く", "example1": "The walls endured the earthquake.", "jp1": "その壁は地震に耐えた。"},
  {"word": "adapt", "correct": "適応する", "choices": ["適応する", "規制する"], "etymology": "ad = 〜へ + apt = 適した", "example1": "Animals adapt to their environment.", "jp1": "動物は環境に適応する。"},
  {"word": "recognize", "correct": "認識する", "choices": ["認識する", "法律を制定する"], "etymology": "re = 再び + cogn = 知る", "example1": "I recognized her immediately.", "jp1": "私は彼女だとすぐにわかった。"},
  {"word": "judge", "correct": "判断する", "choices": ["判断する", "正当化する"], "etymology": "jud = 判断する", "example1": "Do not judge people too quickly.", "jp1": "人をあまり早く判断してはいけない。"},
  {"word": "design", "correct": "設計する", "choices": ["設計する", "正常化する"], "etymology": "de = はっきり + sign = 印をつける", "example1": "She designs websites for small companies.", "jp1": "彼女は小さな会社向けにウェブサイトを設計している。"},
  {"word": "note", "correct": "書き留める", "choices": ["書き留める", "仕える"], "etymology": "not = 印をつける・書き留める", "example1": "Please note the deadline.", "jp1": "締め切りに注意してください。"},
  {"word": "notice", "correct": "気づく", "choices": ["気づく", "保存する"], "etymology": "not = 印をつける", "example1": "Did you notice the change?", "jp1": "その変化に気づきましたか。"},
  {"word": "ascertain", "correct": "確かめる", "choices": ["確かめる", "解放する"], "etymology": "as = 〜へ + certain = 確かな", "example1": "We need to ascertain the facts first.", "jp1": "まず事実を確かめる必要がある。"},
  {"word": "verify", "correct": "確認する", "choices": ["確認する", "支配する"], "etymology": "ver = 真実 + ify = する", "example1": "Please verify your email address.", "jp1": "メールアドレスを確認してください。"},
  {"word": "survive", "correct": "生き残る", "choices": ["生き残る", "脱臼させる"], "etymology": "sur = 上に + vive = 生きる", "example1": "Few plants survive in this heat.", "jp1": "この暑さの中で生き残れる植物は少ない。"}
];
