window.quizData = [
  {"word": "bilingual", "correct": "2言語を話す", "choices": ["2言語を話す", "至る所にある"], "etymology": "bi = 2 + lingual = 言語の", "example1": "Their children are bilingual.", "jp1": "彼らの子どもたちは2言語を話せる。"},
  {"word": "bilateral", "correct": "二国間の", "choices": ["二国間の", "相反する感情をもつ"], "etymology": "bi = 2 + lateral = 側の", "example1": "The two countries signed a bilateral agreement.", "jp1": "その2国は二国間協定に署名した。"},
  {"word": "biweekly", "correct": "2週間ごとの", "choices": ["2週間ごとの", "生態学の"], "etymology": "bi = 2", "example1": "We have a biweekly meeting.", "jp1": "私たちは隔週で会議をしている。"},
  {"word": "semiconscious", "correct": "半分意識のある", "choices": ["半分意識のある", "心的外傷の"], "etymology": "semi = 半分 + conscious = 意識のある", "example1": "He was semiconscious after the fall.", "jp1": "彼は転倒のあと半意識状態だった。"},
  {"word": "productive", "correct": "生産的な", "choices": ["生産的な", "合理的な"], "etymology": "produce = 生み出す + ive = 性質の", "example1": "It was a productive meeting.", "jp1": "それは実りの多い会議だった。"},
  {"word": "readable", "correct": "読みやすい", "choices": ["読みやすい", "財政の"], "etymology": "read + able = できる", "example1": "The text is clear and readable.", "jp1": "その文章は明快で読みやすい。"},
  {"word": "flexible", "correct": "柔軟な", "choices": ["柔軟な", "憲法上の"], "etymology": "flex = 曲げる + ible = できる", "example1": "We need a more flexible schedule.", "jp1": "私たちにはもっと柔軟な予定が必要だ。"},
  {"word": "underpaid", "correct": "低賃金の", "choices": ["低賃金の", "持ち運びできる"], "etymology": "under = 不足して + paid = 支払われた", "example1": "Many care workers are underpaid.", "jp1": "多くの介護労働者は低賃金だ。"},
  {"word": "underdeveloped", "correct": "発展途上の", "choices": ["発展途上の", "攻撃的な"], "etymology": "under = 不足して + developed = 発達した", "example1": "The roads are still underdeveloped in that area.", "jp1": "その地域では道路整備がまだ不十分だ。"},
  {"word": "uphill", "correct": "上り坂の", "choices": ["上り坂の", "徐々の"], "etymology": "up = 上へ + hill = 丘", "example1": "We walked uphill for an hour.", "jp1": "私たちは1時間上り坂を歩いた。"},
  {"word": "downhill", "correct": "下り坂の", "choices": ["下り坂の", "多様な"], "etymology": "down = 下へ + hill = 丘", "example1": "The car rolled downhill.", "jp1": "その車は坂を下って転がった。"},
  {"word": "lifelong", "correct": "生涯にわたる", "choices": ["生涯にわたる", "形式的な"], "etymology": "life + long = 長く", "example1": "Learning should be a lifelong habit.", "jp1": "学びは生涯続く習慣であるべきだ。"},
  {"word": "ambiguous", "correct": "曖昧な", "choices": ["曖昧な", "統一された"], "etymology": "ambi = 両方 + ag = 動く", "example1": "His answer was ambiguous.", "jp1": "彼の答えはあいまいだった。"},
  {"word": "ubiquitous", "correct": "至る所にある", "choices": ["至る所にある", "目に見える"], "etymology": "ubi = どこで + quitous = ある", "example1": "Smartphones are ubiquitous today.", "jp1": "今やスマートフォンはどこにでもある。"},
  {"word": "ambivalent", "correct": "相反する感情をもつ", "choices": ["相反する感情をもつ", "聞こえる"], "etymology": "ambi = 両方 + valent = 力を持つ", "example1": "She felt ambivalent about the offer.", "jp1": "彼女はその申し出に複雑な気持ちだった。"},
  {"word": "ecological", "correct": "生態学の", "choices": ["生態学の", "図の"], "etymology": "eco = 環境 + logical = 〜に関する", "example1": "The project may cause ecological damage.", "jp1": "その計画は生態系に被害を与えるかもしれない。"},
  {"word": "traumatic", "correct": "心的外傷の", "choices": ["心的外傷の", "敏感な"], "etymology": "trauma = 傷", "example1": "It was a traumatic experience.", "jp1": "それは心に傷を残す経験だった。"},
  {"word": "rational", "correct": "合理的な", "choices": ["合理的な", "信用できる"], "etymology": "ratio = 理性・計算", "example1": "Try to make a rational decision.", "jp1": "理性的な判断をしなさい。"},
  {"word": "fiscal", "correct": "財政の", "choices": ["財政の", "信じられない"], "etymology": "fisc = 国庫", "example1": "The government announced a new fiscal policy.", "jp1": "政府は新しい財政政策を発表した。"},
  {"word": "constitutional", "correct": "憲法上の", "choices": ["憲法上の", "連続した"], "etymology": "con = 共に + stitut = 立てる + al = 〜の", "example1": "The court ruled it constitutional.", "jp1": "裁判所はそれを合憲だと判断した。"},
  {"word": "pressure", "correct": "圧力", "choices": ["圧力", "認識"], "etymology": "press = 押す", "example1": "He works well under pressure.", "jp1": "彼はプレッシャーの中でもよく働く。"},
  {"word": "access", "correct": "利用の機会", "choices": ["利用の機会", "位置"], "etymology": "ac = 〜へ + cess = 行く", "example1": "Students need access to good libraries.", "jp1": "生徒たちは良い図書館を利用できる必要がある。"},
  {"word": "predecessor", "correct": "前任者", "choices": ["前任者", "見込み"], "etymology": "pre = 前に + cede = 行く", "example1": "She changed the policy of her predecessor.", "jp1": "彼女は前任者の方針を変えた。"},
  {"word": "attention", "correct": "注意", "choices": ["注意", "展望"], "etymology": "at = 〜へ + tend = 向ける", "example1": "The teacher asked for our attention.", "jp1": "先生は私たちに注意を向けるよう求めた。"},
  {"word": "structure", "correct": "構造", "choices": ["構造", "証拠"], "etymology": "struct = 組み立てる", "example1": "The structure of the bridge is strong.", "jp1": "その橋の構造は頑丈だ。"},
  {"word": "destruction", "correct": "破壊", "choices": ["破壊", "オーディション"], "etymology": "de = 下へ + struct = 壊す", "example1": "The storm caused massive destruction.", "jp1": "その嵐は大きな破壊をもたらした。"},
  {"word": "concept", "correct": "概念", "choices": ["概念", "感覚"], "etymology": "con = 共に + cept = 取る", "example1": "The concept is easy to understand.", "jp1": "その概念は理解しやすい。"},
  {"word": "perception", "correct": "認識", "choices": ["認識", "論理"], "etymology": "per = 通して + ception = 受け取る", "example1": "Public perception changed quickly.", "jp1": "世間の受け止め方はすぐに変わった。"},
  {"word": "position", "correct": "位置", "choices": ["位置", "順序"], "etymology": "pos = 置く", "example1": "She is in a strong position now.", "jp1": "彼女は今、有利な立場にいる。"},
  {"word": "prospect", "correct": "見込み", "choices": ["見込み", "結果"], "etymology": "pro = 前へ + spect = 見る", "example1": "Job prospects are improving.", "jp1": "仕事の見通しは改善している。"},
  {"word": "vision", "correct": "展望", "choices": ["展望", "影響"], "etymology": "vis = 見る", "example1": "The company has a clear vision.", "jp1": "その会社は明確なビジョンを持っている。"},
  {"word": "evidence", "correct": "証拠", "choices": ["証拠", "一部"], "etymology": "e = 外へ + vid = 見る", "example1": "There is no evidence of fraud.", "jp1": "不正の証拠はない。"},
  {"word": "audition", "correct": "オーディション", "choices": ["オーディション", "解決策"], "etymology": "aud = 聞く", "example1": "She passed the audition.", "jp1": "彼女はオーディションに合格した。"},
  {"word": "sensation", "correct": "感覚", "choices": ["感覚", "増加"], "etymology": "sens = 感じる", "example1": "The news caused a sensation.", "jp1": "そのニュースは大騒ぎを引き起こした。"},
  {"word": "logic", "correct": "論理", "choices": ["論理", "減少"], "etymology": "log = 言葉・理屈", "example1": "I cannot follow your logic.", "jp1": "私はあなたの論理が理解できない。"},
  {"word": "sequence", "correct": "順序", "choices": ["順序", "認知"], "etymology": "sequ = 従う", "example1": "Please put the pictures in sequence.", "jp1": "絵を順番どおりに並べてください。"},
  {"word": "consequence", "correct": "結果", "choices": ["結果", "判断"], "etymology": "con = 共に + sequence = 続く", "example1": "Every action has a consequence.", "jp1": "どんな行動にも結果がある。"},
  {"word": "influence", "correct": "影響", "choices": ["影響", "伝記"], "etymology": "in = 中へ + flu = 流れる", "example1": "Parents have a strong influence on children.", "jp1": "親は子どもに強い影響を与える。"},
  {"word": "fraction", "correct": "一部", "choices": ["一部", "アニメーション"], "etymology": "fract = 割る", "example1": "Only a small fraction agreed.", "jp1": "賛成したのはごく一部だけだった。"},
  {"word": "solution", "correct": "解決策", "choices": ["解決策", "精神"], "etymology": "solut = 解く", "example1": "We need a practical solution.", "jp1": "私たちには実用的な解決策が必要だ。"},
  {"word": "increase", "correct": "増加", "choices": ["増加", "呼吸"], "etymology": "in = 上へ + cresc = 成長", "example1": "We saw an increase in demand.", "jp1": "需要の増加が見られた。"},
  {"word": "decrease", "correct": "減少", "choices": ["減少", "法人"], "etymology": "de = 下へ + cresc = 成長", "example1": "There was a sharp decrease in sales.", "jp1": "売上は大幅に減少した。"},
  {"word": "cognition", "correct": "認知", "choices": ["認知", "心理学"], "etymology": "cogn = 知る", "example1": "Music can affect cognition.", "jp1": "音楽は認知に影響を与えることがある。"},
  {"word": "judgment", "correct": "判断", "choices": ["判断", "地域"], "etymology": "jud = 判断", "example1": "Trust your own judgment.", "jp1": "自分自身の判断を信じなさい。"},
  {"word": "biography", "correct": "伝記", "choices": ["伝記", "文明"], "etymology": "bio = 命 + graph = 書く", "example1": "I am reading a biography of Einstein.", "jp1": "私はアインシュタインの伝記を読んでいる。"},
  {"word": "animation", "correct": "アニメーション", "choices": ["アニメーション", "民主主義"], "etymology": "anim = 命", "example1": "The film uses beautiful animation.", "jp1": "その映画は美しいアニメーションを使っている。"},
  {"word": "spirit", "correct": "精神", "choices": ["精神", "政治"], "etymology": "spir = 息", "example1": "The team showed great spirit.", "jp1": "そのチームはすばらしい気迫を見せた。"},
  {"word": "respiration", "correct": "呼吸", "choices": ["呼吸", "年代順"], "etymology": "re = 繰り返し + spir = 息", "example1": "The nurse checked his respiration.", "jp1": "看護師は彼の呼吸を確認した。"},
  {"word": "corporation", "correct": "法人", "choices": ["法人", "地理学"], "etymology": "corp = 体", "example1": "The corporation opened a new branch.", "jp1": "その企業は新しい支店を開いた。"},
  {"word": "psychology", "correct": "心理学", "choices": ["心理学", "幾何学"], "etymology": "psych = 心", "example1": "She is studying psychology at university.", "jp1": "彼女は大学で心理学を学んでいる。"},
  {"word": "region", "correct": "地域", "choices": ["地域", "領土"], "etymology": "reg = 支配・線", "example1": "Rice is grown in this region.", "jp1": "この地域では米が育てられている。"},
  {"word": "civilization", "correct": "文明", "choices": ["文明", "天文学"], "etymology": "civ = 市民", "example1": "Ancient civilization left many ruins.", "jp1": "古代文明は多くの遺跡を残した。"},
  {"word": "democracy", "correct": "民主主義", "choices": ["民主主義", "公平"], "etymology": "demo = 民衆 + cracy = 支配", "example1": "Democracy depends on free elections.", "jp1": "民主主義は自由な選挙に支えられている。"},
  {"word": "politics", "correct": "政治", "choices": ["政治", "状況"], "etymology": "polis = 都市", "example1": "He lost interest in politics.", "jp1": "彼は政治に興味を失った。"},
  {"word": "chronology", "correct": "年代順", "choices": ["年代順", "障害物"], "etymology": "chron = 時間", "example1": "The book explains the chronology of the war.", "jp1": "その本は戦争の年代順を説明している。"},
  {"word": "geography", "correct": "地理学", "choices": ["地理学", "比喩"], "etymology": "geo = 地 + graphy = 記述", "example1": "We studied the geography of South America.", "jp1": "私たちは南アメリカの地理を勉強した。"},
  {"word": "geometry", "correct": "幾何学", "choices": ["幾何学", "圧力"], "etymology": "geo = 地 + metry = 測る", "example1": "He is good at geometry.", "jp1": "彼は幾何が得意だ。"},
  {"word": "territory", "correct": "領土", "choices": ["領土", "利用の機会"], "etymology": "terr = 地", "example1": "The bird defended its territory.", "jp1": "その鳥は自分の縄張りを守った。"},
  {"word": "astronomy", "correct": "天文学", "choices": ["天文学", "前任者"], "etymology": "astro = 星 + nomy = 学問", "example1": "She wants to study astronomy.", "jp1": "彼女は天文学を学びたいと思っている。"},
  {"word": "equity", "correct": "公平", "choices": ["公平", "注意"], "etymology": "equ = 等しい", "example1": "The policy aims to promote equity.", "jp1": "その政策は公平性を促進することを目指している。"},
  {"word": "circumstance", "correct": "状況", "choices": ["状況", "構造"], "etymology": "circum = 周りに + stance = 立つ", "example1": "We had no choice under the circumstances.", "jp1": "その状況では私たちに選択の余地はなかった。"},
  {"word": "obstacle", "correct": "障害物", "choices": ["障害物", "破壊"], "etymology": "ob = 前に + stacle = 立つ", "example1": "Lack of time is the biggest obstacle.", "jp1": "時間不足が最大の障害だ。"},
  {"word": "metaphor", "correct": "比喩", "choices": ["比喩", "概念"], "etymology": "meta = 越えて + phor = 運ぶ", "example1": "The poem uses a powerful metaphor.", "jp1": "その詩は力強い比喩を使っている。"},
  {"word": "transport", "correct": "運ぶ", "choices": ["運ぶ", "押す"], "etymology": "trans = 越えて + port = 運ぶ", "example1": "Transport in the city is efficient.", "jp1": "その都市の交通は効率的だ。"},
  {"word": "import", "correct": "輸入する", "choices": ["輸入する", "圧縮する"], "etymology": "im = 中へ + port = 運ぶ", "example1": "Oil is a major import.", "jp1": "石油は主要な輸入品だ。"},
  {"word": "export", "correct": "輸出する", "choices": ["輸出する", "落ち込ませる"], "etymology": "ex = 外へ + port = 運ぶ", "example1": "Rice is an important export.", "jp1": "米は重要な輸出品だ。"},
  {"word": "transmit", "correct": "送る", "choices": ["送る", "進む"], "etymology": "trans = 越えて + mit = 送る", "example1": "Mosquitoes can transmit disease.", "jp1": "蚊は病気を媒介することがある。"},
  {"word": "emit", "correct": "放つ", "choices": ["放つ", "超える"], "etymology": "e = 外へ + mit = 送る", "example1": "The lamp emits a soft light.", "jp1": "そのランプはやわらかい光を放つ。"},
  {"word": "dismiss", "correct": "退ける", "choices": ["退ける", "卒業する"], "etymology": "dis = 離れて + miss = 送る", "example1": "The judge dismissed the case.", "jp1": "裁判官はその訴えを退けた。"},
  {"word": "conduct", "correct": "行う", "choices": ["行う", "広げる"], "etymology": "con = 共に + duct = 導く", "example1": "He conducted the survey carefully.", "jp1": "彼はその調査を注意深く実施した。"}
];
