window.quizData = [
  {"word": "revive", "correct": "生き返らせる", "choices": ["生き返らせる", "水分を与える"], "etymology": "re = 再び + vive = 生きる", "example1": "The rain revived the flowers.", "jp1": "その雨で花は生き返った。"},
  {"word": "animate", "correct": "活気づける", "choices": ["活気づける", "拡大する"], "etymology": "anim = 命", "example1": "The movie was animated by hand.", "jp1": "その映画は手作業でアニメ化された。"},
  {"word": "inspire", "correct": "鼓舞する", "choices": ["鼓舞する", "減らす"], "etymology": "in = 中へ + spir = 息を吹き込む", "example1": "Her speech inspired the students.", "jp1": "彼女のスピーチは生徒たちを励ました。"},
  {"word": "expire", "correct": "期限が切れる", "choices": ["期限が切れる", "比較する"], "etymology": "ex = 外へ + spir = 息を出す", "example1": "My passport will expire next year.", "jp1": "私のパスポートは来年期限が切れる。"},
  {"word": "manipulate", "correct": "操作する", "choices": ["操作する", "模倣する"], "etymology": "man = 手", "example1": "Do not manipulate other people.", "jp1": "他人を操ってはいけない。"},
  {"word": "impede", "correct": "妨げる", "choices": ["妨げる", "同化する"], "etymology": "im = 中で + pede = 足", "example1": "Traffic jams impede progress.", "jp1": "交通渋滞は進行を妨げる。"},
  {"word": "regulate", "correct": "規制する", "choices": ["規制する", "仲介する"], "etymology": "reg = 支配する・まっすぐにする", "example1": "The law regulates online sales.", "jp1": "その法律はネット販売を規制している。"},
  {"word": "legislate", "correct": "法律を制定する", "choices": ["法律を制定する", "補充する"], "etymology": "legis = 法", "example1": "The government cannot legislate morality.", "jp1": "政府は道徳を法律で定めることはできない。"},
  {"word": "justify", "correct": "正当化する", "choices": ["正当化する", "避難させる"], "etymology": "just = 正しい + ify = する", "example1": "Nothing can justify violence.", "jp1": "何ものも暴力を正当化できない。"},
  {"word": "normalize", "correct": "正常化する", "choices": ["正常化する", "認める"], "etymology": "norm = 基準 + ize = 〜にする", "example1": "We should not normalize rude behavior.", "jp1": "失礼な行動を当たり前にしてはいけない。"},
  {"word": "serve", "correct": "仕える", "choices": ["仕える", "前進する"], "etymology": "serv = 仕える", "example1": "This restaurant serves great pasta.", "jp1": "このレストランはおいしいパスタを出す。"},
  {"word": "preserve", "correct": "保存する", "choices": ["保存する", "くっつく"], "etymology": "pre = 前もって + serve = 保つ", "example1": "We must preserve the forest.", "jp1": "私たちはその森を守らなければならない。"},
  {"word": "liberate", "correct": "解放する", "choices": ["解放する", "誘拐する"], "etymology": "liber = 自由 + ate = 〜にする", "example1": "The soldiers liberated the town.", "jp1": "兵士たちはその町を解放した。"},
  {"word": "dominate", "correct": "支配する", "choices": ["支配する", "そらす"], "etymology": "dom = 支配", "example1": "One company dominates the market.", "jp1": "1社がその市場を支配している。"},
  {"word": "synchronize", "correct": "同期させる", "choices": ["同期させる", "引く"], "etymology": "syn = 共に + chron = 時間", "example1": "Please synchronize your watches.", "jp1": "時計を合わせてください。"},
  {"word": "locate", "correct": "位置づける", "choices": ["位置づける", "監督する"], "etymology": "loc = 場所", "example1": "We finally located the missing file.", "jp1": "私たちはついにその紛失ファイルを見つけた。"},
  {"word": "dislocate", "correct": "脱臼させる", "choices": ["脱臼させる", "重ねる"], "etymology": "dis = 離れて + locate = 場所を定める", "example1": "He dislocated his shoulder.", "jp1": "彼は肩を脱臼した。"},
  {"word": "hydrate", "correct": "水分を与える", "choices": ["水分を与える", "交流する"], "etymology": "hydr = 水", "example1": "Drink water to stay hydrated.", "jp1": "水を飲んで水分を保ちなさい。"},
  {"word": "magnify", "correct": "拡大する", "choices": ["拡大する", "翻訳する"], "etymology": "magn = 大きい + fy = する", "example1": "This lens magnifies small objects.", "jp1": "このレンズは小さな物を拡大する。"},
  {"word": "diminish", "correct": "減らす", "choices": ["減らす", "下見する"], "etymology": "di = 小さく + min = 小さい", "example1": "Their influence has diminished.", "jp1": "彼らの影響力は弱まった。"},
  {"word": "compare", "correct": "比較する", "choices": ["比較する", "準備する"], "etymology": "com = 共に + par = 等しい", "example1": "Compare the two pictures.", "jp1": "その2枚の絵を比べなさい。"},
  {"word": "simulate", "correct": "模倣する", "choices": ["模倣する", "回避する"], "etymology": "simil = 似ている", "example1": "The software simulates flight conditions.", "jp1": "そのソフトは飛行状態を再現する。"},
  {"word": "assimilate", "correct": "同化する", "choices": ["同化する", "循環する"], "etymology": "as = 〜へ + simil = 似せる", "example1": "New students quickly assimilated into school life.", "jp1": "新しい生徒たちはすぐに学校生活になじんだ。"},
  {"word": "mediate", "correct": "仲介する", "choices": ["仲介する", "妨害する"], "etymology": "medi = 中間", "example1": "She tried to mediate the dispute.", "jp1": "彼女はその争いの仲裁をしようとした。"},
  {"word": "replenish", "correct": "補充する", "choices": ["補充する", "紹介する"], "etymology": "re = 再び + plen = 満たす", "example1": "Please replenish the water bottles.", "jp1": "水のボトルを補充してください。"},
  {"word": "evacuate", "correct": "避難させる", "choices": ["避難させる", "解読する"], "etymology": "e = 外へ + vac = 空にする", "example1": "The police evacuated the building.", "jp1": "警察はその建物から人々を避難させた。"},
  {"word": "admit", "correct": "認める", "choices": ["認める", "排除する"], "etymology": "ad = 〜へ + mit = 送る", "example1": "He admitted his mistake.", "jp1": "彼は自分の誤りを認めた。"},
  {"word": "advance", "correct": "前進する", "choices": ["前進する", "侵入する"], "etymology": "ad = 〜へ + vance = 進む", "example1": "Technology continues to advance.", "jp1": "技術は進歩し続けている。"},
  {"word": "adhere", "correct": "くっつく", "choices": ["くっつく", "挿入する"], "etymology": "ad = 〜へ + here = くっつく", "example1": "The label will not adhere to wet glass.", "jp1": "そのラベルはぬれたガラスにはくっつかない。"},
  {"word": "abduct", "correct": "誘拐する", "choices": ["誘拐する", "姿を消す"], "etymology": "ab = 離れて + duct = 導く", "example1": "The police rescued the abducted child.", "jp1": "警察は誘拐された子どもを救出した。"},
  {"word": "avert", "correct": "そらす", "choices": ["そらす", "切り離す"], "etymology": "a = 離れて + vert = 向ける", "example1": "They averted a serious crisis.", "jp1": "彼らは深刻な危機を回避した。"},
  {"word": "subtract", "correct": "引く", "choices": ["引く", "嫌う"], "etymology": "sub = 下から + tract = 引く", "example1": "Please subtract five from ten.", "jp1": "10から5を引いてください。"},
  {"word": "supervise", "correct": "監督する", "choices": ["監督する", "団結させる"], "etymology": "super = 上から + vise = 見る", "example1": "A teacher will supervise the test.", "jp1": "教師がその試験を監督する。"},
  {"word": "superimpose", "correct": "重ねる", "choices": ["重ねる", "増やす"], "etymology": "super = 上に + impose = 置く", "example1": "The app can superimpose one image on another.", "jp1": "そのアプリは画像を重ね合わせることができる。"},
  {"word": "interact", "correct": "交流する", "choices": ["交流する", "つなぐ"], "etymology": "inter = 互いに + act = 行う", "example1": "Children learn by interacting with others.", "jp1": "子どもは他人と関わることで学ぶ。"},
  {"word": "translate", "correct": "翻訳する", "choices": ["翻訳する", "結びつける"], "etymology": "trans = 越えて + lat = 運ぶ", "example1": "Can you translate this into Japanese?", "jp1": "これを日本語に訳してくれますか。"},
  {"word": "preview", "correct": "下見する", "choices": ["下見する", "伝達する"], "etymology": "pre = 前に + view = 見る", "example1": "We previewed the new website.", "jp1": "私たちは新しいウェブサイトを事前に見た。"},
  {"word": "prepare", "correct": "準備する", "choices": ["準備する", "働きすぎる"], "etymology": "pre = 前に + pare = 整える", "example1": "Students prepared for the exam.", "jp1": "生徒たちは試験の準備をした。"},
  {"word": "circumvent", "correct": "回避する", "choices": ["回避する", "追い越す"], "etymology": "circum = 周りを + vent = 行く", "example1": "They tried to circumvent the rule.", "jp1": "彼らはその規則を回避しようとした。"},
  {"word": "circulate", "correct": "循環する", "choices": ["循環する", "見落とす"], "etymology": "circum = 周りに + late = 運ぶ", "example1": "Warm air circulates through the room.", "jp1": "暖かい空気が部屋の中を循環する。"},
  {"word": "obstruct", "correct": "妨害する", "choices": ["妨害する", "過大評価する"], "etymology": "ob = 前に + struct = 積み上げる", "example1": "A fallen tree obstructed the road.", "jp1": "倒れた木が道路をふさいだ。"},
  {"word": "introduce", "correct": "紹介する", "choices": ["紹介する", "過小評価する"], "etymology": "intro = 中へ + duce = 導く", "example1": "Let me introduce myself.", "jp1": "自己紹介させてください。"},
  {"word": "decode", "correct": "解読する", "choices": ["解読する", "支える"], "etymology": "de = 外して + code = 暗号", "example1": "The computer decoded the message.", "jp1": "そのコンピューターは暗号を解読した。"},
  {"word": "eliminate", "correct": "排除する", "choices": ["排除する", "格上げする"], "etymology": "e = 外へ + limin = 境界", "example1": "We must eliminate waste.", "jp1": "私たちは無駄をなくさなければならない。"},
  {"word": "invade", "correct": "侵入する", "choices": ["侵入する", "格下げする"], "etymology": "in = 中へ + vade = 進む", "example1": "The army invaded the country.", "jp1": "その軍はその国に侵攻した。"},
  {"word": "insert", "correct": "挿入する", "choices": ["挿入する", "数で上回る"], "etymology": "in = 中へ + sert = 入れる", "example1": "Insert the key here.", "jp1": "ここに鍵を差し込みなさい。"},
  {"word": "disappear", "correct": "姿を消す", "choices": ["姿を消す", "よりよくやる"], "etymology": "dis = 離れて + appear = 現れる", "example1": "The sun disappeared behind the clouds.", "jp1": "太陽は雲の後ろに隠れた。"},
  {"word": "disconnect", "correct": "切り離す", "choices": ["切り離す", "予見する"], "etymology": "dis = 離して + connect = つなぐ", "example1": "Please disconnect the charger.", "jp1": "充電器を外してください。"},
  {"word": "dislike", "correct": "嫌う", "choices": ["嫌う", "実証する"], "etymology": "dis = 否定 + like = 好む", "example1": "I dislike spicy food.", "jp1": "私は辛い食べ物が好きではない。"},
  {"word": "unite", "correct": "団結させる", "choices": ["団結させる", "譲歩する"], "etymology": "uni = 1", "example1": "The crisis united the community.", "jp1": "その危機が地域社会を一つにした。"},
  {"word": "multiply", "correct": "増やす", "choices": ["増やす", "裏付ける"], "etymology": "multi = 多い + ply = 重なる", "example1": "Bacteria multiply quickly.", "jp1": "細菌はすぐに増殖する。"},
  {"word": "connect", "correct": "つなぐ", "choices": ["つなぐ", "提唱する"], "etymology": "con = 共に + nect = 結ぶ", "example1": "This road connects two towns.", "jp1": "この道は2つの町をつないでいる。"},
  {"word": "combine", "correct": "結びつける", "choices": ["結びつける", "断言する"], "etymology": "com = 共に + bine = 二つ", "example1": "We combined the two files.", "jp1": "私たちは2つのファイルをまとめた。"},
  {"word": "communicate", "correct": "伝達する", "choices": ["伝達する", "批准する"], "etymology": "com = 共に + mun = 分かち合う", "example1": "We need to communicate better.", "jp1": "私たちはもっとよく意思疎通する必要がある。"},
  {"word": "overwork", "correct": "働きすぎる", "choices": ["働きすぎる", "運ぶ"], "etymology": "over = 過剰に + work = 働く", "example1": "Do not overwork yourself.", "jp1": "働きすぎてはいけない。"},
  {"word": "overtake", "correct": "追い越す", "choices": ["追い越す", "輸入する"], "etymology": "over = 越えて + take = 取る", "example1": "A truck overtook us on the highway.", "jp1": "トラックが高速道路で私たちを追い越した。"},
  {"word": "overlook", "correct": "見落とす", "choices": ["見落とす", "輸出する"], "etymology": "over = 上から + look = 見る", "example1": "Our room overlooks the sea.", "jp1": "私たちの部屋から海が見渡せる。"},
  {"word": "overestimate", "correct": "過大評価する", "choices": ["過大評価する", "送る"], "etymology": "over = 過剰に + estimate = 見積もる", "example1": "Do not overestimate your strength.", "jp1": "自分の力を過大評価してはいけない。"},
  {"word": "underestimate", "correct": "過小評価する", "choices": ["過小評価する", "放つ"], "etymology": "under = 不足して + estimate = 見積もる", "example1": "Never underestimate your opponent.", "jp1": "相手を決して過小評価してはいけない。"},
  {"word": "uphold", "correct": "支える", "choices": ["支える", "退ける"], "etymology": "up = 上へ + hold = 保つ", "example1": "The court upheld the decision.", "jp1": "裁判所はその判決を支持した。"},
  {"word": "upgrade", "correct": "格上げする", "choices": ["格上げする", "行う"], "etymology": "up = 上へ + grade = 段階", "example1": "We upgraded the computer system.", "jp1": "私たちはコンピューターシステムを更新した。"},
  {"word": "downgrade", "correct": "格下げする", "choices": ["格下げする", "生み出す"], "etymology": "down = 下へ + grade = 段階", "example1": "The airline downgraded our seats.", "jp1": "航空会社は私たちの座席を格下げした。"},
  {"word": "outnumber", "correct": "数で上回る", "choices": ["数で上回る", "教育する"], "etymology": "out = より上に + number = 数", "example1": "Women outnumber men in this class.", "jp1": "このクラスでは女子が男子より多い。"},
  {"word": "outperform", "correct": "よりよくやる", "choices": ["よりよくやる", "注入する"], "etymology": "out = より上に + perform = 行う", "example1": "This engine outperforms the old one.", "jp1": "このエンジンは旧型より高性能だ。"},
  {"word": "foresee", "correct": "予見する", "choices": ["予見する", "拒絶する"], "etymology": "fore = 前もって + see = 見る", "example1": "Nobody could foresee the accident.", "jp1": "その事故を予見できた人はいなかった。"},
  {"word": "substantiate", "correct": "実証する", "choices": ["実証する", "投影する"], "etymology": "substance = 実体 + iate = 〜にする", "example1": "You must substantiate your claim.", "jp1": "自分の主張を裏づけなければならない。"},
  {"word": "concede", "correct": "譲歩する", "choices": ["譲歩する", "反対する"], "etymology": "con = 共に + cede = 行く・譲る", "example1": "He finally conceded defeat.", "jp1": "彼はついに敗北を認めた。"},
  {"word": "corroborate", "correct": "裏付ける", "choices": ["裏付ける", "引きつける"], "etymology": "cor = 共に + robor = 強い → 強める", "example1": "The witness corroborated her story.", "jp1": "その証人は彼女の話を裏づけた。"},
  {"word": "advocate", "correct": "提唱する", "choices": ["提唱する", "契約する"], "etymology": "ad = 〜へ + voc = 呼ぶ", "example1": "Many doctors advocate regular exercise.", "jp1": "多くの医師が定期的な運動を勧めている。"},
  {"word": "assert", "correct": "断言する", "choices": ["断言する", "抜き出す"], "etymology": "as = 〜へ + sert = 置く", "example1": "She asserted her independence.", "jp1": "彼女は自分の自立を主張した。"},
  {"word": "ratify", "correct": "批准する", "choices": ["批准する", "注意をそらす"], "etymology": "rat = 計算・確認 + ify = 〜にする", "example1": "The senate ratified the treaty.", "jp1": "上院はその条約を批准した。"}
];
