window.quizData = [
  {"word": "portable", "correct": "持ち運びできる", "choices": ["持ち運びできる", "その後の"], "etymology": "port = 運ぶ + able = できる", "example1": "This printer is small and portable.", "jp1": "このプリンターは小さくて持ち運びできる。"},
  {"word": "aggressive", "correct": "攻撃的な", "choices": ["攻撃的な", "何気ない"], "etymology": "ag = 〜へ + gress = 進む", "example1": "The dog became aggressive when strangers came near.", "jp1": "見知らぬ人が近づくと、その犬は攻撃的になった。"},
  {"word": "gradual", "correct": "徐々の", "choices": ["徐々の", "安定した"], "etymology": "grad = 段階", "example1": "There was a gradual increase in sales.", "jp1": "売上は徐々に増加した。"},
  {"word": "diverse", "correct": "多様な", "choices": ["多様な", "流ちょうな"], "etymology": "di = 別々に + verse = 向く", "example1": "The city has a diverse population.", "jp1": "その都市には多様な人々が住んでいる。"},
  {"word": "formal", "correct": "形式的な", "choices": ["形式的な", "遠く離れた"], "etymology": "form = 形", "example1": "Please wear formal clothes to the ceremony.", "jp1": "式にはフォーマルな服を着てください。"},
  {"word": "uniform", "correct": "統一された", "choices": ["統一された", "触れることのできる"], "etymology": "uni = 1つ + form = 形", "example1": "The walls were painted a uniform color.", "jp1": "壁は統一した色で塗られていた。"},
  {"word": "visible", "correct": "目に見える", "choices": ["目に見える", "強制的な"], "etymology": "vis = 見る + ible = できる", "example1": "The moon was clearly visible tonight.", "jp1": "今夜は月がはっきり見えた。"},
  {"word": "audible", "correct": "聞こえる", "choices": ["聞こえる", "耐久性のある"], "etymology": "aud = 聞く + ible = できる", "example1": "Her voice was barely audible.", "jp1": "彼女の声はかすかに聞こえた。"},
  {"word": "graphic", "correct": "図の", "choices": ["図の", "意識している"], "etymology": "graph = 書く・描く", "example1": "The report included a graphic description of the accident.", "jp1": "その報告書には事故の生々しい描写が含まれていた。"},
  {"word": "sensitive", "correct": "敏感な", "choices": ["敏感な", "認知の"], "etymology": "sens = 感じる", "example1": "My skin is sensitive to sunlight.", "jp1": "私の肌は日光に敏感だ。"},
  {"word": "credible", "correct": "信用できる", "choices": ["信用できる", "司法の"], "etymology": "cred = 信じる + ible = できる", "example1": "She gave a credible explanation.", "jp1": "彼女は信頼できる説明をした。"},
  {"word": "incredible", "correct": "信じられない", "choices": ["信じられない", "確かな"], "etymology": "in = 否定 + credible = 信じられる", "example1": "It was an incredible performance.", "jp1": "それは信じられないほどすばらしい演技だった。"},
  {"word": "consecutive", "correct": "連続した", "choices": ["連続した", "検証できる"], "etymology": "con = 共に + secutive = 続いていく", "example1": "He worked for ten consecutive days.", "jp1": "彼は10日連続で働いた。"},
  {"word": "subsequent", "correct": "その後の", "choices": ["その後の", "生分解性の"], "etymology": "sub = 後から + sequent = 従う", "example1": "Subsequent events proved him right.", "jp1": "その後の出来事が彼の正しさを示した。"},
  {"word": "casual", "correct": "何気ない", "choices": ["何気ない", "抗生物質の"], "etymology": "cas = 落ちる", "example1": "He wore casual clothes to the party.", "jp1": "彼はパーティーにカジュアルな服を着て行った。"},
  {"word": "stable", "correct": "安定した", "choices": ["安定した", "身体の"], "etymology": "sta = 立つ", "example1": "The patient's condition is stable now.", "jp1": "その患者の容体は今は安定している。"},
  {"word": "fluent", "correct": "流ちょうな", "choices": ["流ちょうな", "心の"], "etymology": "flu = 流れる", "example1": "She speaks fluent English.", "jp1": "彼女は英語を流ちょうに話す。"},
  {"word": "remote", "correct": "遠く離れた", "choices": ["遠く離れた", "規則的な"], "etymology": "re = 離れて + mot = 動く", "example1": "They live in a remote village.", "jp1": "彼らは遠く離れた村に住んでいる。"},
  {"word": "tangible", "correct": "触れることのできる", "choices": ["触れることのできる", "合法の"], "etymology": "tang = 触れる + ible = できる", "example1": "We need tangible results.", "jp1": "私たちには目に見える結果が必要だ。"},
  {"word": "compulsory", "correct": "強制的な", "choices": ["強制的な", "正当な"], "etymology": "com = 強く + puls = 押す", "example1": "Education is compulsory in Japan.", "jp1": "日本では教育は義務だ。"},
  {"word": "durable", "correct": "耐久性のある", "choices": ["耐久性のある", "不当な"], "etymology": "dur = 続く + able = できる", "example1": "This bag is light but durable.", "jp1": "このバッグは軽いが丈夫だ。"},
  {"word": "conscious", "correct": "意識している", "choices": ["意識している", "異常な"], "etymology": "con = 共に + scious = 知っている", "example1": "She was conscious after the accident.", "jp1": "彼女は事故のあと意識があった。"},
  {"word": "cognitive", "correct": "認知の", "choices": ["認知の", "自由主義の"], "etymology": "cogn = 知る", "example1": "Reading improves cognitive skills.", "jp1": "読書は認知能力を高める。"},
  {"word": "judicial", "correct": "司法の", "choices": ["司法の", "市民の"], "etymology": "jud = 判断する", "example1": "The case is now in the judicial system.", "jp1": "その事件は今、司法制度の中にある。"},
  {"word": "certain", "correct": "確かな", "choices": ["確かな", "国内の"], "etymology": "cert = 確かな", "example1": "I am certain of the answer.", "jp1": "私はその答えに確信がある。"},
  {"word": "verifiable", "correct": "検証できる", "choices": ["検証できる", "支配的な"], "etymology": "ver = 真実 + ify = する + able = できる", "example1": "The claim is not verifiable.", "jp1": "その主張は検証できない。"},
  {"word": "biodegradable", "correct": "生分解性の", "choices": ["生分解性の", "民主的な"], "etymology": "bio = 命 + degradable = 分解できる", "example1": "We should use biodegradable bags.", "jp1": "私たちは生分解性の袋を使うべきだ。"},
  {"word": "antibiotic", "correct": "抗生物質の", "choices": ["抗生物質の", "人口統計の"], "etymology": "anti = 反対 + bio = 命", "example1": "The doctor prescribed an antibiotic.", "jp1": "医者は抗生物質を処方した。"},
  {"word": "corporal", "correct": "身体の", "choices": ["身体の", "一時的な"], "etymology": "corp = 体", "example1": "Many schools banned corporal punishment.", "jp1": "多くの学校は体罰を禁止した。"},
  {"word": "psychic", "correct": "心の", "choices": ["心の", "同時代の"], "etymology": "psych = 心", "example1": "Some people claim to have psychic powers.", "jp1": "自分には霊能力があると主張する人もいる。"},
  {"word": "regular", "correct": "規則的な", "choices": ["規則的な", "時間の"], "etymology": "reg = まっすぐにする", "example1": "Regular exercise is important.", "jp1": "定期的な運動は大切だ。"},
  {"word": "legal", "correct": "合法の", "choices": ["合法の", "地球の"], "etymology": "leg = 法", "example1": "Is it legal to park here?", "jp1": "ここに駐車するのは合法ですか。"},
  {"word": "legitimate", "correct": "正当な", "choices": ["正当な", "水力発電の"], "etymology": "leg = 法", "example1": "That is a legitimate concern.", "jp1": "それは正当な懸念だ。"},
  {"word": "unjust", "correct": "不当な", "choices": ["不当な", "熱の"], "etymology": "un = 否定 + just = 正しい", "example1": "The decision was unjust.", "jp1": "その決定は不当だった。"},
  {"word": "abnormal", "correct": "異常な", "choices": ["異常な", "壮大な"], "etymology": "ab = 離れて + normal = 普通の", "example1": "The test results were abnormal.", "jp1": "検査結果は異常だった。"},
  {"word": "liberal", "correct": "自由主義の", "choices": ["自由主義の", "最小の"], "etymology": "liber = 自由", "example1": "She has liberal views on education.", "jp1": "彼女は教育について自由主義的な考えを持っている。"},
  {"word": "civil", "correct": "市民の", "choices": ["市民の", "同等の"], "etymology": "civ = 市民", "example1": "Please keep the discussion civil.", "jp1": "どうか礼儀正しく話し合ってください。"},
  {"word": "domestic", "correct": "国内の", "choices": ["国内の", "似ている"], "etymology": "dom = 家", "example1": "This flight is domestic, not international.", "jp1": "この便は国際便ではなく国内便だ。"},
  {"word": "dominant", "correct": "支配的な", "choices": ["支配的な", "豊富な"], "etymology": "dom = 支配", "example1": "English is the dominant language online.", "jp1": "英語はオンラインで支配的な言語だ。"},
  {"word": "democratic", "correct": "民主的な", "choices": ["民主的な", "空いている"], "etymology": "demo = 民衆 + cratic = 支配に関する", "example1": "They want a more democratic system.", "jp1": "彼らはもっと民主的な制度を求めている。"},
  {"word": "demographic", "correct": "人口統計の", "choices": ["人口統計の", "中世の"], "etymology": "demo = 民衆 + graphic = 記述された", "example1": "The report describes major demographic changes.", "jp1": "その報告書は主な人口構成の変化を述べている。"},
  {"word": "temporary", "correct": "一時的な", "choices": ["一時的な", "不在の"], "etymology": "tempor = 時間", "example1": "This office is only temporary.", "jp1": "この事務所は一時的なものにすぎない。"},
  {"word": "contemporary", "correct": "同時代の", "choices": ["同時代の", "抽象的な"], "etymology": "con = 共に + temporary = 同時代の", "example1": "She studies contemporary art.", "jp1": "彼女は現代美術を学んでいる。"},
  {"word": "temporal", "correct": "時間の", "choices": ["時間の", "下位の"], "etymology": "tempor = 時間", "example1": "We need a clear temporal order of events.", "jp1": "私たちには出来事の明確な時間順が必要だ。"},
  {"word": "terrestrial", "correct": "地球の", "choices": ["地球の", "上位の"], "etymology": "terr = 地", "example1": "Humans are terrestrial animals.", "jp1": "人間は陸上の動物だ。"},
  {"word": "hydroelectric", "correct": "水力発電の", "choices": ["水力発電の", "国際的な"], "etymology": "hydro = 水 + electric = 電気", "example1": "The country relies on hydroelectric power.", "jp1": "その国は水力発電に頼っている。"},
  {"word": "thermal", "correct": "熱の", "choices": ["熱の", "先史時代の"], "etymology": "thermo = 熱", "example1": "The camera detects thermal energy.", "jp1": "そのカメラは熱エネルギーを感知する。"},
  {"word": "magnificent", "correct": "壮大な", "choices": ["壮大な", "戦後の"], "etymology": "magn = 大きい", "example1": "We enjoyed a magnificent view.", "jp1": "私たちは壮大な景色を楽しんだ。"},
  {"word": "minimum", "correct": "最小の", "choices": ["最小の", "明らかな"], "etymology": "min = 小さい", "example1": "The minimum age is eighteen.", "jp1": "最低年齢は18歳だ。"},
  {"word": "equivalent", "correct": "同等の", "choices": ["同等の", "並外れた"], "etymology": "equ = 等しい + valent = 力を持つ", "example1": "One euro is roughly equivalent to 160 yen.", "jp1": "1ユーロはおよそ160円に相当する。"},
  {"word": "similar", "correct": "似ている", "choices": ["似ている", "課外の"], "etymology": "simil = 似ている", "example1": "The two ideas are very similar.", "jp1": "その2つの考えはとても似ている。"},
  {"word": "plentiful", "correct": "豊富な", "choices": ["豊富な", "違法な"], "etymology": "plen = 満ちた", "example1": "Fresh water is plentiful here.", "jp1": "ここでは新鮮な水が豊富だ。"},
  {"word": "vacant", "correct": "空いている", "choices": ["空いている", "不規則な"], "etymology": "vac = 空", "example1": "The apartment has been vacant for months.", "jp1": "そのアパートは何か月も空き家のままだ。"},
  {"word": "medieval", "correct": "中世の", "choices": ["中世の", "活動していない"], "etymology": "medi = 中間 + eval = 時代", "example1": "We visited a medieval castle.", "jp1": "私たちは中世の城を訪れた。"},
  {"word": "absent", "correct": "不在の", "choices": ["不在の", "過度に活動的な"], "etymology": "ab = 離れて + sent = ある", "example1": "Two students were absent today.", "jp1": "今日は2人の生徒が欠席した。"},
  {"word": "abstract", "correct": "抽象的な", "choices": ["抽象的な", "極めて敏感な"], "etymology": "ab = 離れて + tract = 引く", "example1": "Love is an abstract idea.", "jp1": "愛は抽象的な考えだ。"},
  {"word": "subordinate", "correct": "下位の", "choices": ["下位の", "独特な"], "etymology": "sub = 下に + ordinate = 並べる", "example1": "He has a subordinate role in the team.", "jp1": "彼はチームの中で従属的な役割にある。"},
  {"word": "superior", "correct": "上位の", "choices": ["上位の", "2言語を話す"], "etymology": "super = 上に", "example1": "This model is superior to the old one.", "jp1": "この型は旧型より優れている。"},
  {"word": "international", "correct": "国際的な", "choices": ["国際的な", "二国間の"], "etymology": "inter = 間に + national = 国家の", "example1": "The airport is an international hub.", "jp1": "その空港は国際的な拠点だ。"},
  {"word": "prehistoric", "correct": "先史時代の", "choices": ["先史時代の", "2週間ごとの"], "etymology": "pre = 前に + historic = 歴史の", "example1": "They found a prehistoric tool.", "jp1": "彼らは先史時代の道具を見つけた。"},
  {"word": "postwar", "correct": "戦後の", "choices": ["戦後の", "半分意識のある"], "etymology": "post = 後に + war = 戦争", "example1": "The city changed rapidly in the postwar period.", "jp1": "その都市は戦後に急速に変化した。"},
  {"word": "obvious", "correct": "明らかな", "choices": ["明らかな", "生産的な"], "etymology": "ob = 前に + via = 道", "example1": "The answer is obvious.", "jp1": "答えは明らかだ。"},
  {"word": "extraordinary", "correct": "並外れた", "choices": ["並外れた", "読みやすい"], "etymology": "extra = 外に・超えて + ordinary = 普通の", "example1": "She showed extraordinary courage.", "jp1": "彼女は並外れた勇気を示した。"},
  {"word": "extracurricular", "correct": "課外の", "choices": ["課外の", "柔軟な"], "etymology": "extra = 外に + curricular = 課程の", "example1": "He joined several extracurricular activities.", "jp1": "彼はいくつかの課外活動に参加した。"},
  {"word": "illegal", "correct": "違法な", "choices": ["違法な", "低賃金の"], "etymology": "il = 否定 + legal = 法律の", "example1": "It is illegal to sell alcohol to children.", "jp1": "子どもに酒を売るのは違法だ。"},
  {"word": "irregular", "correct": "不規則な", "choices": ["不規則な", "発展途上の"], "etymology": "ir = 否定 + regular = 規則正しい", "example1": "His heartbeat was irregular.", "jp1": "彼の心拍は不規則だった。"},
  {"word": "inactive", "correct": "活動していない", "choices": ["活動していない", "上り坂の"], "etymology": "in = 否定 + active = 活動的な", "example1": "The volcano is inactive now.", "jp1": "その火山は今は活動していない。"},
  {"word": "hyperactive", "correct": "過度に活動的な", "choices": ["過度に活動的な", "下り坂の"], "etymology": "hyper = 過剰 + active = 活動的な", "example1": "The child became hyperactive after the drink.", "jp1": "その子はその飲み物のあとで過度に活発になった。"},
  {"word": "hypersensitive", "correct": "極めて敏感な", "choices": ["極めて敏感な", "生涯にわたる"], "etymology": "hyper = 過剰 + sensitive = 敏感な", "example1": "He is hypersensitive to noise.", "jp1": "彼は音に過敏だ。"},
  {"word": "unique", "correct": "独特な", "choices": ["独特な", "曖昧な"], "etymology": "uni = 1", "example1": "Each snowflake is unique.", "jp1": "雪の結晶はどれも唯一無二だ。"}
]; 
